### ISSUE TITLE
CSOM PeoplePicker loginname encoding problem in on-prem scenario

### ISSUE THREAD

**Issue by MattiasLindberg** [SharePoint/PnP#1150]
I use the CSOM People Picker to select users in an on-prem SharePoint farm. The problem is that the loginname is incorrectly encoded both when displayed in the client and when retrieving the value for processing.

Below is an example picture of what it looks like when you debug in Visual Studio. The HTML dynamically rendered by JavaScript has a single \ which makes it into an escape character. In many cases this is just silently because e.g. \s doesn't have any meaning, but as the example below show a problem occur when the username starts with an U. \u is the start of an encoded hax value...

But even if the problem doesn't appear while rendering the search result there is still a problem when you select a value. Because the \ disappears and what should have been domain\sqwerty becomes domainsqwerty when you try to read the value.

![js error](https://cloud.githubusercontent.com/assets/9967919/9514105/52362708-4c97-11e5-8e48-98f3a7059db0.png)

My workaround has been do change PeoplePickerHelper.cs/GetPeoplePickerSearchData to return content with more .
return clientResult.Value.Replace("\\", "\\\\");

This fix is similar to what has been done in peoplepickercontrol.js/PeoplePicker.prototype.ConstructResolvedUserSpan where \ is transformed to \\.

I will try to submit this change to the source code also!

**Comment by patrick-rodgers** [comment]
yes, please do submit the fix and tie it back to this issue, then we can close the issue and know it is resolved. Thanks,

Patrick

**Comment by BrianMichely** [comment]
Hey Mattias,
Just circling back on this one to see if you had implemented the fix mentioned above?

Brian
