### ISSUE TITLE
Displaying terms under a certain term

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/PnP#1181]
Hi Guys,

I think we missed an important functionality here on the taxonomy control, in SP 2013 we can specify in list column taxonomy to only show terms under a certain term like in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/6864547/10128212/d1dff3f2-65f2-11e5-889b-39a6ad100a56.png)

The current version only able to display terms under termset.

Can we extend this script to perform this functionality?

Cheers

**Comment by VesaJuvonen** [comment]
Thx jonathanhotono,
I'm not 100% for what this is exactly referring, since it mentions also "script". Is this around PnP Provisioning engine and PowerShell support or something around that or related on some other sample in the PnP program?

Thanks for the additional information advance.

**Comment by jonathanhotono** [comment]
Hi VesaJuvonen,

Sorry I am not quite sure where to raise this issue, but I am referring to this script:
https://github.com/OfficeDev/PnP/tree/master/Components/Core.TaxonomyPicker/Core.TaxonomyPickerWeb

Thanks

Jonathan
