### ISSUE TITLE
Taxonomy.Picker trigger change

### ISSUE THREAD

**Issue by stact** [SharePoint/PnP#1216]
Hi,
For next versions could you provide a trigger events when value change?

For example when you put selected value on hidden Field

``` javascript
this._hiddenValidated.val(JSON.stringify(this._selectedTerms)).trigger('change')
```

And you wanna catch the event: 

``` javascript
jQuery('input[type="hidden"]').change(function () {
// Do something
});
```

I dont know if it's the best way.
Thank you for your feedback

**Comment by CBuntrock** [comment]
I agree, this would be a very helpful feature to extract or validate the values right after selection...
