### ISSUE TITLE
UserMulti does not create a multi user field on-Premises 2013 

### ISSUE THREAD

**Issue by dpalfery** [SharePoint/PnP#1280]
When provisioning a new Field in a Site or on a List  the UserMulti is created as a single user field. 

Server Farm on build 15.0.4719.1002

**Comment by kilasuit** [comment]
This has been a long lasting issue with the underlying CSOM  - not sure that its ever been resolved as is an engineering issue not an PnP issue see issue raised in the PnP-PowerShell Repo https://github.com/OfficeDev/PnP-PowerShell/issues/59

Also I spent hours refactoring and retrying to get this to work - but it just doesnt seem to be available unless its recently changed @VesaJuvonen @jansenbe - I'm not sure as I haven't been keeping a tab on the latest CSOM releases.

**Comment by shurick81** [comment]
Anybody can solve/investigate this?

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1023

**Comment by VesaJuvonen** [comment]
Relocating to Core repository for final verification. Hopefully already fully functional at this point.
