### ISSUE TITLE
Unable to open many app projects in VS 2015 Community

### ISSUE THREAD

**Issue by shalinparmar** [SharePoint/PnP#1299]
I am unable to open many PnP projects in Visual Studio 2015 Community on my Windows 10 machine. Can someone please help? Is it due to "Add-in" template instead of "App" template?

e.g. I am unable to open any Provision...... projects and many others.

I would appreciate quick response.

**Comment by rroman81** [comment]
I am unsure about the Community SKU, but you do need the Office Development tools installed via WebPI. Did you make sure you have that installed?

**Comment by shalinparmar** [comment]
Yes I do have it installed and running VS 2015 Update 1. I am able to open a few App projects but not many of them. for e.g. Provisioning.Cloud.Async gives error:

![image](https://cloud.githubusercontent.com/assets/13654332/12779414/dd5279c6-ca8d-11e5-9928-f76f0009e4f5.png)

**Comment by jansenbe** [comment]
https://www.visualstudio.com/en-us/products/compare-visual-studio-2015-products-vs shows that you need to install the Office developers tools manually in case of the Community SKU. These developers tools can be found here: http://aka.ms/OfficeDevToolsForVS2015

**Comment by shalinparmar** [comment]
It is already installed as I can open few other app projects but not most of them. Please see the images below:
![image](https://cloud.githubusercontent.com/assets/13654332/12780925/02617b82-ca97-11e5-990d-4febb11eaf8d.png)
![image](https://cloud.githubusercontent.com/assets/13654332/12780937/220a1d72-ca97-11e5-8f8c-e63100b248f7.png)

**Comment by hcdocsdev** [comment]
I'm having the same trouble:

- Using Visual Studio Community 2015 Update 1, Windows 8.1
- Uninstalled Office Developer Tools preview - same error
- Then uninstalled and reinstalled Office Developer Tools update 1 - same error

Solutions with a regular and "web" project (like Core.EventReceivers) seem to load the web project okay but not the other. I'm not a coder and would be grateful for any tips. Thanks Microsoft for these amazing tools.

![2016-02-12 18_47_23-core embedjavascriptjsom - microsoft visual studio](https://cloud.githubusercontent.com/assets/15255009/13042211/aafe5a7a-d37b-11e5-9482-ddd2a3124fe0.png)

**Comment by shalinparmar** [comment]
Does anyone have found the root cause of why the App projects are not opening in VS 2015 Community?

**Comment by CEStar** [comment]
I HAVE EXACLY THE SAME ISSUE. CAN SOMEONE PLEASE, PLEASE, PLEASE PROVIDE A WORKAROUND. (E.G. OPEN A FILE LIKE THE *.csproj OR THE *.sln FILE AND CHANGE PROPERTIES MANUALLY)

**Comment by HariprasathPremraj** [comment]
I was able to get this working with the following changes to .csproj file of sharepoint solution.

<TargetOfficeVersion>15.0</TargetOfficeVersion>

and

<PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
  
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>

for me in my csproj file "VSToolsPath" element was outside the "PropertyGroup" element so I moved it inside that element.

    After doing this I reloaded the solution and set the sharepoint part of the solution as the start up project. This helped me resolve the issue.

   Hopefully this helps someone.

Happy Coding,
Hari

**Comment by kkrzaczkowski** [comment]
I've also the same problem and after some changes its gone.
In my case probably it was problem with publishing profile.

I Removed from Web project:
- <None Include="Properties\PublishProfiles\Outlook.pubxml" />

Also Removed from manifest project:
- <ActivePublishProfile>OutlookSMS</ActivePublishProfile>
-  <ItemGroup>
    <ProjectReference Include="..\OutlookWebAddIn3Web\OutlookWebAddIn3Web.csproj">....

**Comment by VesaJuvonen** [comment]
Just updated https://github.com/SharePoint/PnP/tree/dev/Samples/Branding.ClientSideRendering solution to work properly also with Community version. Some of the samples are pretty old and unfortunately community version does not automatically upgrade them properly to latest VS version, which can cause challenges with the add-in model templates. I'll close this one now as too generic issue, but if anyone has any issues with the solutions, please open a new issue with sample details and we'll update that accordingly as needed. Thanks everyone for your patience and input around this topic.
