### ISSUE TITLE
Fields not readable and/or writable in User-Service

### ISSUE THREAD

**Issue by codingfreak** [SharePoint/PnP#1314]
I'm using source from the [OfficeDevPnP.MSGraphAPIDemo](https://github.com/OfficeDev/PnP/tree/master/Samples/MicrosoftGraph.Office365.Generic) solution. Whenever I try to write the birthday inside of one of my user profiles it gives me an exception:

```
{
  "error": {
    "code": "-1, Microsoft.SharePoint.Client.UnknownError",
    "message": "Unbekannter Fehler.",
    "innerError": {
      "request-id": "cb261564-afeb-4608-a534-de4feb506b76",
      "date": "2016-02-19T16:04:18"
    }
  }
}
```

The method and URL are

```
PATCH https://graph.microsoft.com/v1.0/users/{MyUPN}
```

My request body generated by JSON.NET looks like this:

```
{"birthday":"1970-08-15T00:00:00+01:00"}
```

As stated [here](http://graph.microsoft.io/de-de/docs/api-reference/v1.0/api/user_update) this should be sufficent to update the birtday.

I can however fire the update for other properties like

```
{"country":"Somecountry"}
```

The problem is that those changes are not stored in O365. I can read everything so that this shouldn't be an issue regarding Open ID Connect or OAuth. I checked on all delegated permissions in Azure Portal for my Application (35 currently) and I'm not getting 403 like I do when there is an OAuth problem.

**Comment by VesaJuvonen** [comment]
One thing to confirm is that they user profile property is still editable in your tenant as well. Would also double check the used code with some other tenant, so that we can scope down the issue around is it tenant specific configuration issue or generic issue in Graph.

**Comment by VesaJuvonen** [comment]
Closing this issue due no follow up discussions.
