### ISSUE TITLE
PeoplePicker issue for user names with apostrophe

### ISSUE THREAD

**Issue by janemrivera** [SharePoint/PnP#1353]
Regarding the PeoplePickerControl.js

I have a provider hosted app. One of the fields in the page is a people picker. When I type in a name with an apostrophe (') like O'Donnell or O'Brien, the list of recommended users come up. However, I am unable to select any user. The user selection box just stays displayed.

**Comment by praswa426** [comment]
I faced the same issue and done some work around. Now it works fine for me.

**Comment by janemrivera** [comment]
What was the work around?  Did you make any changes on the peoplepickercontrol.js file?

**Comment by janemrivera** [comment]
Any input is much appreciated.  We still have this issue. Thanks.

**Comment by praswa426** [comment]
Hi,

We need to modify the code in 2 places..

1. In RecipientSelected method
2. In QuerySuccess method


Only highlighted code needs to be modified.



*Place 1 :*

// Update the people picker control to show the newly added user

CsomPeoplePicker.prototype.RecipientSelected = function (login, name,
email) {

this.HideSelectionBox();

// Push new resolved user to list

*this.PushResolvedUser(this.ResolvedUser(login, name.replace(/##/g, '\''),
email));*

// Update the resolved user display

this.PeoplePickerControl.html(this.ResolvedUsersToHtml());

// Prepare the edit control for a second user selection

this.PeoplePickerEdit.val('');

this.PeoplePickerEdit.focus();

}



Place 2:

-------

CsomPeoplePicker.prototype.QuerySuccess = function (queryNumber,
searchResult) {


//var results =
this.SharePointContext.parseObjectFromJsonString(searchResult.get_value());


var results = $.parseJSON(searchResult);


var txtResults = '';


var baseDisplayTemplate = '<div class=\'ms-bgHoverable\' style=\'width:
400px; padding: 4px;\' onclick=\'javascript:{0}.RecipientSelected(\"{1}\",
\"{4}\", \"{3}\")\'>{2}';


var displayTemplate = '';


if (this.ShowLoginName && this.ShowTitle) {


displayTemplate = baseDisplayTemplate + ' ({5})<br/>{6}</div>';


} else if (this.ShowLoginName || this.ShowTitle) {


displayTemplate = baseDisplayTemplate + ' ({6})</div>';


} else {


displayTemplate = baseDisplayTemplate + '</div>';



}


if (results) {


if (results.length > 0) {


// if this function is not the callback from the last issued query then
just ignore it. This is needed to ensure a matching between


// what the user entered and what is shown in the query feedback window


if (queryNumber < this._lastQueryID) {


return;



}


var displayCount = results.length;


if (displayCount > this.MaxEntriesShown) {


displayCount = this.MaxEntriesShown;



}


for (var i = 0; i < displayCount; i++) {


var item = results[i];


var loginName = item['Key'];


var displayName = item['DisplayText'];


var title = item['EntityData']['Title'];


var email = item['EntityData']['Email'];


* txtResults += this.Format(displayTemplate, this.InstanceName, loginName,
displayName, email, displayName.replace(/'/g, '##'),
loginName.split('|')[2], title);*



}



On Fri, Mar 18, 2016 at 12:43 PM, janemrivera <notifications@github.com>
wrote:

> Any input is much appreciated. We still have this issue. Thanks.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/OfficeDev/PnP/issues/1353#issuecomment-198514372>
>



-- 


*Regards,*
*Pradeep Kumar Varanasi*
*Senior SharePoint Developer**M: (661)379-5133*

<https://www.linkedin.com/in/pradeepkumarvaranasi>

**Comment by federicoruiz** [comment]
Hi, @praswa426, first thanks for the help. I'm having the same problem, and can't find any solution for this, inlusive the code that you provide to change in the library peoplepicker.js doesn't works for me.

In my case, only change the apostrophes with numerals (##)

Example: Katie O##Leary (katie@tfsqa.onmicrosoft.com)

But the control still unable to select the the user.

I'm working with this issue, so If someone have another approach to resolve this I would like to learn about that.

**Comment by federicoruiz** [comment]
My teammate did the following changes in the next three methods to fix the issue, so you can replace the methods by this:

        // HTML encoder
        PeoplePicker.prototype.HtmlEncode = function (html) {
            var value = document.createElement('a').appendChild(document.createTextNode(html)).parentNode.innerHTML;
            return escape(value);
        }

        // HTML decoder
        PeoplePicker.prototype.HtmlDecode = function (html) {
            var a = document.createElement('a');
            a.innerHTML = html;
            var value = a.textContent;
            return unescape(value);
        }

        // Update the people picker control to show the newly added user
        PeoplePicker.prototype.RecipientSelected = function (login, name, email) {
            this.HideSelectionBox();
            // Push new resolved user to list
            this.PushResolvedUser(this.ResolvedUser(login, this.HtmlDecode(name), email));
            // Update the resolved user display 
            this.PeoplePickerControl.html(this.ResolvedUsersToHtml());
            // Prepare the edit control for a second user selection
            this.PeoplePickerEdit.val('');
            this.PeoplePickerEdit.focus();
            this.PeoplePickerData.change();
        }

**Comment by ShachiSattigeri** [comment]
Hi All,
we have issue with deletion of the users with apostrophe in email ID, after selection . Kindly let me know, if there is work around fix similar to above.
