### ISSUE TITLE
Responsive samples should be consolidated

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP#1357]
Responsive samples should be consolidated to have only ONE version of the truth. Currently there's tree different solutions. 

Simplistic - https://github.com/OfficeDev/PnP/tree/master/Samples/Branding.InjectResponsiveCSS
SPO - https://github.com/OfficeDev/PnP-partner-pack - medium
on-prem UI package - https://github.com/OfficeDev/PnP-Tools/tree/master/Solutions/SharePoint.UI.Responsive

SharePoint.UI.Responsive works in SPO already as it is. We should have only one package to maintain. Best option is to drop the old sample from PnP and start using the latest one which works for on-prem and SPO.

**Comment by ciphertxt** [comment]
This would be great. There's often a bit of a disconnect for SharePoint practitioners as to what packages to apply (and when). One package would would certainly lessen that confusion.

**Comment by cveld** [comment]
Do we have a list of all requirements we want to cover? E.g. why couldn't we just remove the first two, and leave the latter?

**Comment by VesaJuvonen** [comment]
All solutions have been updated to use the PnP CSOM Core component based solution. InjectResponsiveCSS sample now updated to dev branch and released as part of the Dec release on 9th of Dec.
