### ISSUE TITLE
Injecting Secondary navigation using OD4B.NavLinksInjection not working properly on Chrome 

### ISSUE THREAD

**Issue by german1983** [SharePoint/PnP#1377]
After implementing the [example ](https://github.com/OfficeDev/PnP/tree/master/Samples/OD4B.NavLinksInjection)everything is working on IE, but on Chrome the ribbon is disabled s you can see in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/9931269/13884754/2b62b570-ed0e-11e5-854a-8ba67e4a32d6.png)

On the other hand, everything is working as expected on IE:

![image](https://cloud.githubusercontent.com/assets/9931269/13884798/53e30fa4-ed0e-11e5-8ea1-645656933ef6.png)

Is there anything I can do to support both IE and Chrome ?

Thanks

**Comment by VesaJuvonen** [comment]
I just tested with Chrome and had no issues in SharePoint Online. Can you provide more environmental details around this, so that we can reproduce the issue. thx.

**Comment by VesaJuvonen** [comment]
Since there's no response on the requested information, closing this one for now.
