### ISSUE TITLE
GetFile extension method error

### ISSUE THREAD

**Issue by icecubemint** [SharePoint/PnP#1451]
Hello! From the end of the last week I receive the following error when using GetFile() extension method: _Method not found: 'Void Microsoft.SharePoint.Client.ClientRuntimeContext.set_DisableReturnValueCache(Boolean)'. at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) at Microsoft.SharePoint.Client.FileFolderExtensions.GetFile(Folder folder, String fileName) ._

I'm trying to get a file from folder by name:
 _var fileToUpload = folderToUpload.GetFile(fileName);_

It worked before but now this error is thrown. I tried to update the nuget package but it didn't help.

**Comment by VesaJuvonen** [comment]
Relocating to Core repository for further check. Most likely already solved issue, but good to double check.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1022
