### ISSUE TITLE
cdlUtil object does not Initialized

### ISSUE THREAD

**Issue by mrajpurohit** [SharePoint/PnP#1481]
#### Environment

[ ] Office 365 / SharePoint Online

`$(function () {

```
//create instance of library
cdlUtil = new CrossDomainUtil();

//initialize library
cdlUtil.Init(ServerUrl + "/SharePoint/proxy?SPHostUrl=" + SPHostUrl);

//execute code when the library is initialized
cdlUtil.OnInitialized(function () {

 // My Code

 });
});
```

 `
I have two button on Index view Add and Remove, the is wrapped in fn call from index im able to make call once after the App page has loaded, however when in click on Remove button the library object cdlUtil is never initialized. It is always false. This may be bug!

**Comment by VesaJuvonen** [comment]
thx mrajpurohit, could you also share the exact sample / solution this is referring to. If it's on native SharePoint APIs, then we can't really fix that through PnP initiative.

**Comment by VesaJuvonen** [comment]
Since there's no response on requested details, will close up the issue.
