### ISSUE TITLE
Error while synching site admins and external users

### ISSUE THREAD

**Issue by AnoojNair** [SharePoint/PnP#1482]
Hi,

I found a bug in the code which replaces the existing site admins and external user.

Method : ReplaceExistedUsers
File :GovernanceDbContext.cs

Following worked for me

`public void ReplaceExistedUsers(ICollection<SiteUser> users)
        {
            if (users == null)
                return;
            var removeList = new LinkedList<SiteUser>();
            var addList = new LinkedList<SiteUser>();
            foreach (var user in users)
            {
                var existedUser = Users.FirstOrDefault(u => u.LoginName == user.LoginName);
                if (existedUser != null)
                {
                    removeList.AddLast(existedUser);
                    addList.AddLast(user);
                }
            }
            foreach(var user in removeList)
                Users.Remove(user);
            foreach(var user in addList)
                Users.Add(user);
        }``

**Comment by VesaJuvonen** [comment]
thx Anooj, sorry for small delay but could you provide also the solution / sample details, so that we can pin-point the VS solution this is referring to. Thx.

**Comment by VesaJuvonen** [comment]
Due no response on the provided question, will close up the issue.
