### ISSUE TITLE
Access Request List - OneDrive | External Sharing

### ISSUE THREAD

**Issue by sumitgarg03** [SharePoint/PnP#1489]
Hi All

We are working on development of a solution to implement External Sharing Timer, for items shared with External users in OneDrive for Business sites, on the lines of (https://github.com/OfficeDev/PnP/tree/master/Solutions/Governance.ExternalSharingTimer). 

Initially we were using/capturing external share details from Access Request List of each OneDrive for Business site for our implementation, as we required sharing details of each item/file/folder. But recently Microsoft has implemented a design change(Microsoft confirmed the design change) and we have observed a new behavior in Access Request List. Now when we share a file to the same external user, who already accepted the invitation for some  other item on that particular site and is part of the site, is not tracked by access request list. Earlier we were getting an entry in access request list for each time we share an item with same external user. As data captured from Access Request List was being used as primary input to our proposed solution, we are not able to proceed with further development.

Did anyone has encountered a similar issue or figured an alternate solution for this issue or have implemented a similar requirement? Is there any other way to capture the external share details of all items inside all of the OneDrive for Business sites under a tenant? Any suggestion would be of great help. Thanks in advance.

Best Regards,
Sumit Garg

**Comment by sumitgarg03** [comment]
Hi All

Could anyone please help me with the above issue? Thanks in advance.

Regards,
Sumit Garg

**Comment by absoluteg** [comment]
We are looking to know if anyone has experienced this same issue as presenting this solution from being used now.  Is there an alternative to this solution?  I thought MS was working on similar functionality built-in to both OneDrive and SharePoint Online.  Can we confirm that OneDrive for Business has changed how it tracks external shares across OneDrive for a particular user and that removing an external user on OneDrive For Business share removes it across all the rest the user was shared with?

Please let us know if the functionality of this project no longer works based on recent MS changes in data stored behind the scenes in hidden lists/columns.  Or can the project be updated and reflect the back end changes and continue to be a viable solution?

Thanks,
Greg Jones
