### ISSUE TITLE
Core.UserProfiles.Sync - Custom Azure extension attribute not mapping

### ISSUE THREAD

**Issue by GroFinJarryd** [SharePoint/PnP#1500]
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP
  Core.UserProfiles.Sync
#### Category

[ ] Bug
#### Environment

[ ] Office 365 / SharePoint Online
#### Expected or Desired Behavior

Mapping Custom Attribute does not work
In the Property Configuration I am trying to map an Azure AD Extension Attribute - 
extension_{_GUID_}_dateOfBirth however I receive Object reference not set to an instance of an object.
Exception thrown: 'System.NullReferenceException' in Core.UserProfiles.Sync.exe

I can see the Attribute in the Graph Explorer https://graphexplorer.cloudapp.net/ after userType:

```
  "userType": "Member",
  "extension_{GUID}_dateOfBirth": "1986-04-09T00:00:00Z"
},
```

Not to sure if I have provided enough information or if I am doing something wrong

**Comment by pariom** [comment]
I had the same problem.
I fix it by replacing the line
var propertyNewValue = typeof(GraphApi.User).GetProperty(prop.ADAttributeName).GetValue(user);
on
var propertyNewValue = user.GetExtendedProperties()[prop.ADAttributeName]; 
But now it works for extension attributes only.

**Comment by somartin90** [comment]
I have the same problem, I can not recover the customAttributes.
Any help or alternative solution will be well received.

Thanks.

**Comment by JunioraTm** [comment]
Retrieve custom / extension attributes is two-fold:

1. First, you have to make sure that any of the extensionAttributes# you utilize in AD are being synchronized to Azure AD. This process is different than for the Exchange Online profile (Msol) which converts them to CustomAttribute#.

- Opening the "AD Connect" application, sign in, click next a few times until you get to configuration screens. Then open Sync > Optional Features and check "Directory extension attribute sync".
- Afterwards, find your custom extensionAttributes and under Sync > Directory Extensions, select them
Reference: [Directory Extension Attribute Sync](https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-get-started-custom#directory-extension-attribute-sync)
- You can verify everything is ready by using the AzureAD module, then Connect-AzureAD and get a user and expand their Extension Property. Should be extension_[GUID]_extensionAttribute#.

2. Next, once the profile properties have synchronized to AzureAD, you have to modify the PnP UserProfiles.Sync > Program.cs. I used @pariom solution above and added an extra null check. So it checks if it is a basic property first, then will attempt to get it as an extended property.

```
var propertyNew = typeof(GraphApi.User).GetProperty(prop.ADAttributeName);
var propertyNewValue = (propertyNew != null ? propertyNew.GetValue(user) : null);

if (propertyNewValue == null)
{
     propertyNewValue = user.GetExtendedProperties()[prop.ADAttributeName];
}
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
