### ISSUE TITLE
How to initiate values to the field?

### ISSUE THREAD

**Issue by wahabmajboor** [SharePoint/PnP#1501]
#### Which PnP repository to report the issue?

-https://github.com/OfficeDev/PnP/tree/master/Components/Core.TaxonomyPicker
#### Category

[ ] Enhancement
#### Environment

[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
CU March 2016

I have added the component successfully on the page by using JavaScript approach and I can use the taxonomy picker to add terms into the document metadata field. I want to load the update-page and try to initiate the taxonomy picker within terms of the document. It is always empty. How can I load the component with pre-selected terms from document metadata field using javascript?

I am using pnp solutions for the first time and I am sorry if I put my request on wrong place.
Please advise me if I did not  it  from good way or approach.
Thanks in advance,
Wahab

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
