### ISSUE TITLE
Core.LargeFileUpload Using JavaScript for uploading files larger than 2GB to SharePoint Online

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP#1503]
I have a custom form which creates a project list item in a custom list. This form allows you to upload documents and it saves them using REST to a document library and those documents are associated with the created project using a lookup. 

I have a requirement where I need to enable a client to upload a files larger than 2GB which is the current SharePoint Online REST API limit. 

This [page](https://github.com/OfficeDev/PnP/tree/master/Samples/Core.LargeFileUpload#large-file-handling---option-3-startupload-continueupload-and-finishupload) describes how this can be accomplished using **StartUpload, ContinueUpload and FinishUpload**

I'd like to attempt this but using JavaScript. Is this possible at all?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
