### ISSUE TITLE
PnP Self service site collection provisioning solution not sending email

### ISSUE THREAD

**Issue by Manal-Ochir** [SharePoint/PnP#1525]
#### Which PnP repository to report the issue?

https://github.com/OfficeDev/PnP/tree/master/Solutions/Provisioning.UX.App
#### Category

[ ] Bug
#### Environment

[ ] Office 365 / SharePoint Online
#### Expected or Desired Behavior

Send success email message after site is created.
#### Observed Behavior

No email is received
#### Steps to Reproduce

In Azure WebJob logs this error is appearing 

[Provisioning.Common.Mail.EmailHelper.SendNewSiteSuccessEmail] There was an error sending email. The exception is System.FormatException: An invalid character was found in the mail header: ':'.

Users in recipient field have claims encoding prefix (i:0#...). Changing code in Provisioning.Job.SiteProvisioningJob fixed this issue.
![image](https://cloud.githubusercontent.com/assets/20277502/18428374/45265d5a-78d6-11e6-85b8-e1d283b3faab.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
