### ISSUE TITLE
Problem with Core.Settings.LocaleAndLanguiage

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP#1532]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[X ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: SP2013 Sp1 August 2016 CU
#### Expected or Desired Behavior

Using Core.Settings.LocaleAndLanguage  first command should be a  GET in which case the redirect in Page_PreInit method of default.aspx.cs should work.
#### Observed Behavior

Using Core.Settings.LocaleAndLanguage  first command seems to be a POST rather than a GET in which case the redirect in Page_PreInit method of default.aspx.cs does not work. (I get an error "An error occurred while processing your request") If I use https Ihave a certificate problem.  Click on ignore it and still get the same problem.
#### Steps to Reproduce

Compile and Debug Core.Settings.LocaleAndLanguage sample.

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
