### ISSUE TITLE
Missing pages content with CSOM GetProvisioningTemplate output vs PS output

### ISSUE THREAD

**Issue by nickdelrosario** [SharePoint/PnP#1535]
**Which PnP repository to report the issue?**
SharePointPnPCoreOnline v2.7.1609.3 - Provisioning Engine

**Category**

[ ] Bug

**Environment**

[ ] Office 365 / SharePoint Online

**Expected or Desired Behavior**

Create Provisioning Template with default page content and composed look

**Observed Behavior**

Generated XML template is missing pages content. PowerShell command for the same request generated properly.

**Steps to Reproduce**

Here is the sample CSOM Code I run vs PS:
            //Provision Site Directory Site
            //TODO: Change to Dynamcially pull from request list
            Uri templateURI = new Uri("https://nickdelrosario.sharepoint.com/sites/templatesteamsite2");
            ProvisioningTemplate template = null;

```
        //Get the realm for the URL
        string templateRealm = TokenHelper.GetRealmFromTargetUrl(templateURI);

        //Get the access token for the URL.  
        //   Requires this app to be registered with the tenant
        string accessToken = TokenHelper.GetAppOnlyAccessToken(
            TokenHelper.SharePointPrincipal,
            templateURI.Authority, templateRealm).AccessToken;

        //Get client context with access token
        using (var templateCtx =
            TokenHelper.GetClientContextWithAccessToken(
                templateURI.ToString(), accessToken))
        {

            ProvisioningTemplateCreationInformation templateCI = new ProvisioningTemplateCreationInformation(templateCtx.Web);
            FileSystemConnector fileSystemConnector = new FileSystemConnector(String.Format(@"{0}\..\..\Templates",
                                        AppDomain.CurrentDomain.BaseDirectory), "");

            templateCI.FileConnector = fileSystemConnector;
            templateCI.PersistBrandingFiles = true;
            templateCI.ProgressDelegate = (message, step, total) =>
            {
                Console.WriteLine("{0}/{1}\t{2}", step, total, message);
            };

            template = templateCtx.Web.GetProvisioningTemplate(templateCI);

            XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(String.Format(@"{0}\..\..\Templates",
                                        AppDomain.CurrentDomain.BaseDirectory), "");
            provider.SaveAs(template, "TeamSiteTemplate.xml");
```

**Powershell:**
<img width="1036" alt="ps screengrab" src="https://cloud.githubusercontent.com/assets/22508898/18934722/f7a74c9c-85a0-11e6-98d9-f2c792912189.PNG">

**See XML outputs that differ:**
CSOM
[CSOMGenerated.txt](https://github.com/OfficeDev/PnP/files/499385/CSOMGenerated.txt)

PS
[PSGenerated.txt](https://github.com/OfficeDev/PnP/files/499386/PSGenerated.txt)

**Comment by petepuu** [comment]
Hi,

I have exactly the same problem against SharePoint 2016. If I export template in PS like below the pages and pagecontents is included but what I just realized is that it only exports the welcome page! None of the other pages I have in SitePages library are not exported
![image](https://cloud.githubusercontent.com/assets/8307644/21672617/2f854a78-d32c-11e6-9ec4-10376e5d971f.png)




Testing using console app with similar CSOM code the template file is basically empty
![image](https://cloud.githubusercontent.com/assets/8307644/21672964/9a993ca0-d32e-11e6-983d-e775edbd5a5a.png)


**PowerShell**
[ps_sts0.txt](https://github.com/SharePoint/PnP/files/686699/ps_sts0.txt)

**CSOM**
[csom_sts0.txt](https://github.com/SharePoint/PnP/files/686700/csom_sts0.txt)

**Comment by petepuu** [comment]
I did some debugging of PageContents handler and found out that this is caused by WillExtract method which checks is the ClientContext.Credentials defined. In my CSOM test using console application I do not explicitly set the credentials, so this method will return FALSE

![image](https://cloud.githubusercontent.com/assets/8307644/22309971/33c0f9d6-e356-11e6-957f-85db9f6424c0.png)

But if setting credentials in console app for example like below then it works of course in a same way than in PowerShell version where credentials are passed

![image](https://cloud.githubusercontent.com/assets/8307644/22309902/f2a7233a-e355-11e6-883b-35ecb9430623.png)

I guess that this check can be removed? I still need to test this in my site provisioning add-in with app-only permissions by defining the _willExtract to be always TRUE.

Pete

**Comment by VesaJuvonen** [comment]
This really comes down on app-only vs user context usage. We will absolutely have a look on this more closely to see the root cause of the issue. Since this however is related on the PnP Core Component, I'll relocate this issue to right repository, so that the issue does not get lost.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1021
