### ISSUE TITLE
PnP/Samples/Core.SitePermissions/ fails to authenticate

### ISSUE THREAD

**Issue by rrkushner** [SharePoint/PnP#1536]
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP
  Core.SitePermissions

_You can delete this section after you have confirmed target repository for your submission._
#### Category

It doesn't work for me.
#### Environment

[ ] Office 365 / SharePoint Online

In Program.cs, at List<UserEntity> admins = cc.Web.GetAdministrators();
I get:

"An unhandled exception of type 'System.Xml.XmlException' occurred in System.Xml.dll

Additional information: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method."

I think it is failing to authenticate. I think it isn't even sending an authentication header (according to what I see in Fiddler).

**Comment by VesaJuvonen** [comment]
Hi rrkushner,
I just updated used NuGet package for this sample and tested that things are working as expected. There's updated sample version in the dev branch. Closing since works as expected now.
