### ISSUE TITLE
AspNetCore.Authentication - High Trust Support

### ISSUE THREAD

**Issue by veebz** [SharePoint/PnP#1537]
#### Category

[ ] Bug
[X ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[X ] SharePoint 2016
[X ] SharePoint 2013
#### Expected or Desired Behavior

Add support for High Trust scenarios to the ASP.NET Core Authentication/Authorization Middleware in the AspNetCore.Authentication solution. It looks like this is a [Todo](https://github.com/OfficeDev/PnP/blob/f735139f22ab9f415ca0c876961710630f44267c/Solutions/AspNetCore.Authentication/src/OfficeDevPnP.Core.Framework.Authentication/SharePointContext.cs#L766), but I could not find an existing issue for this functionality.

**Comment by coryisakson** [comment]
I also need this functionality. Thanks!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
