### ISSUE TITLE
SharePointControllerExtensions clientContext returning Null - object reference not set to instance error

### ISSUE THREAD

**Issue by enterpriseguru1** [SharePoint/PnP#1545]
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP

PNP Master > Solutions >
BusinessApps.CorporateEventsApp
#### Category

[ ] Bug
#### Environment

[ ] Office 365 / SharePoint Online
#### Expected or Desired Behavior

line 12 of SharePointControllerExtensions.cs should return clientContext
#### Observed Behavior

adding user to event registration dialog and saving calls line 12 of SharePointControllerExtensions.cs for clientContext.  But clientContext is returning Null - object reference not set to instance error.
#### Steps to Reproduce

adding user to event registration dialog and saving.  Using SharePoint Online and Visual Studio localhost for provider hosted.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
