### ISSUE TITLE
Cannot provision file (home.aspx) from template xml by CSOM ApplyTemplateProvisioning

### ISSUE THREAD

**Issue by khha** [SharePoint/PnP#1555]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[ ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ V] SharePoint 2013

I have an SharePoint App Part. In this app part I try to do ApplyTemplateProvisioning. I have an xml file where I try to provision a file. This file is in the same folder as the template xml file. I got this error:

`Value cannot be null exception`

This is my template xml file:

```
<pnp:Files>
        <pnp:File Src="Home.aspx" Folder="{site}/Paginas" Overwrite="true">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:Welkomstpagina}" />
            <pnp:Property Key="Title" Value="Home" />
            <pnp:Property Key="PublishingPageLayout" Value="{masterpagecatalog}{site}/BlankWebPartPage.aspx, Lege pagina met webonderdelen" />
            <pnp:Property Key="PublishingIsFurlPage" Value="False" />
            <pnp:Property Key="RobotsNoIndex" Value="False" />
            <pnp:Property Key="PublishingPageContent" Value="&lt;h1&gt;​​Welkom op de Periode!&lt;{site}h1&gt;" />
          </pnp:Properties>
        </pnp:File>
      </pnp:Files>
```

This is the CSOM code:

```
private bool ApplyProvisioningTemplate(Web newWeb)
        {
            XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(String.Format(@"{0}\Templates\", AppDomain.CurrentDomain.BaseDirectory), "");

            if (provider != null)
            {
                var template = provider.GetTemplate("PeriodeTemplate.xml");

                if (template != null)
                {
                    newWeb.ApplyProvisioningTemplate(template);

                    return true;
                }
            }

            return false;
        }
```

What is going wrong? I try this with pnp powershell and is working fine. When I try this with CSOM pnp code it doesnt work.

**Comment by erwinvanhunen** [comment]
From a quick scan I notice that you do not set the connector on the template:

template.Connector = provider.Connector;

This will allow the engine to know where to retrieve any additional files you specify in the template.

**Comment by khha** [comment]
thanks, it works!
