### ISSUE TITLE
PnP provisioning engine CSOM with Multi Factor Authentication tenant

### ISSUE THREAD

**Issue by athrayee** [SharePoint/PnP#1561]
I am trying to use PnP Provisioning engine to create site based on a template. The tenant that I am connecting to to create the site is using Multi Factor Authentication. I don't see a obvious way to authenticate and proceed with creation of sites based on tempalte. Could you please help me here with either sample or an approach to tackle this issue. I am using .NET C# in CSOM in a Console app.

**Comment by DeanGross** [comment]
Not sure about how to do that in C#, but you can use the PnP Connect-PnPonline with the useweblogin param, see https://github.com/OfficeDev/PnP-PowerShell/blob/master/Documentation/ConnectPnPOnline.md

**Comment by camiloborges** [comment]
And you can/should  use App Credentials if you are running this as a
background job.
There are/were some limitations with AppCreds, such as provisioning of
termsets. does anyone know what are the limitations currently?

**Comment by VesaJuvonen** [comment]
Since there's no comments after the community assistance, we are assuming that the issue has been resolved. Thx everyone for participating on the discussion, input absolutely appreciated and the suggested solutions are valid for the MFA cases.
