### ISSUE TITLE
Core.ProfilePictureUploader can't get pics from Exchange - auth issue

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP#1565]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Issue details
https://github.com/OfficeDev/PnP/tree/master/Samples/Core.ProfilePictureUploader has a note around getting images directly from the Exchange with URL for the SharePoint. This does not however work due authentication issues towards the Exchange REST. Would be good to see if we can sign-in automatically or using a prompt for getting access on the pics from Exchange, which has been sync'd from AAD.

Uploading of the images from local sources is working property towards SharePoint online.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
