### ISSUE TITLE
"Provisioning.Extensibility" sample doesn't work with latest PnP Core version

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/PnP#1569]
#### Category
 - [x] Bug

#### Environment
 - [x] Office 365 / SharePoint Online
 - [x] SharePoint 2016 any CU
 - [x] SharePoint 2013 any CU

#### Expected or Desired Behavior
`Provisioning.Extensibility` should add new Page based on page layout. 

#### Observed Behavior
Exception "Unable to convert Int32 to String[]" thrown. 

#### Steps to Reproduce
Run the sample (update creds before).

**Comment by jansenbe** [comment]
Thanks for this PR Sergei, looks good so we'll test and merge this one.
