### ISSUE TITLE
Creating from template resolves jslink URL tokens

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/PnP#1577]
System: Sharepoint Online

When creating a new subsite from a template, whereas the template has web parts with jslink in it, sharepoint automatically resolves any URL tokens used (e.g. `~sitecollection`) for the newly created site. This breaks the jslink effectively because the URLs don't work if they are relatively specified (e.g. `/sites/sitecol/...`.

Is there a way to either prevent this from happening or to change it after it has happened? Because the creation is user trigger CSOM/JSON can't be used.

Any ideas?

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1018

**Comment by VesaJuvonen** [comment]
Issue moved to right repository. Closing on this side.
