### ISSUE TITLE
 Issue with Deleting Site collections

### ISSUE THREAD

**Issue by suz7777** [SharePoint/PnP#1578]
####Which PnP repository should you use to report the issue?####
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[x ] Bug
[x] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online

if we do the following:

•	Create a site collection via PNP with the Site Collection URL – ie: corpBG04
o	A site collection is created
o	A site collection termstore group is created – for example: Site Collection - tenantname.sharepoint.com-sites-corpBG04
•	We delete a site collection
o	Remove-SPOSite $siteCollectionUrl
o	Remove-SPODeletedSite $siteCollectionUrl
•	We re-create a site collection via PNP with the same Site Collection URL – ie: corpBG04
o	The site collection is re-created
o	A site collection termstore is created – for example: Site Collection - tenantname.sharepoint.com-sites-corpBG04-1
	NOTE: The original termstore still exists – but is not visable via Site Settings- Term Store Management Tool - Site Collection - tenantname.sharepoint.com-sites-corpBG04
o	We rename the new termstore (remove the -1 from the site collection termstore name) to Site Collection - tenantname.sharepoint.com-sites-corpBG04
o	Use PNP to create term sets
o	When we use the PNP to provision the site columns and content types, we link to the termsets created for the site collection
•	Use code to access termstore
o	var taxSession = SP.Taxonomy.TaxonomySession.getTaxonomySession(ctx);
o	var termStore = taxSession.getDefaultSiteCollectionTermStore();
o	var termSetCollection = termStore.getTermSetsByName(termSetName, 1033);
o	var termSet = termSetCollection.getByName(termSetName);
o	var terms = termSet.getAllTerms();
o	ctx.load(terms, "Include(IsRoot, Labels, TermsCount, CustomSortOrder, Id, IsAvailableForTagging, Name, PathOfTerm, Parent, TermSet.Name, CustomProperties, LocalCustomProperties)");
o	ctx.executeQueryAsync()
o	These commands return the ORIGINAL termstore and data – not the new termset we renamed.

We need to know how to do the following:
•	 Remove-SPOSiteCollectionTermSet $termSetName
•	Remove-SPOSite $siteCollectionUrl
•	Remove-SPODeletedSite $siteCollectionUrl

OR we need the remove-sposite to also delete the termset

We also need to know how to do the following:
•	Remove an ORPHANED termstore that still exists after we deleted and recreated a site collection (basically clean up these site collections)

Thanks!
suz

**Comment by suz7777** [comment]
here is how we would do this on premise: http://www.thesharepointbar.com/?p=432

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-PowerShell#718

**Comment by VesaJuvonen** [comment]
Issue relocated to right repository, so closing this one - https://github.com/SharePoint/PnP-PowerShell/issues/718
