### ISSUE TITLE
Method not found: 'Void Microsoft.SharePoint.Client.Web.set_IsMultilingual(Boolean)

### ISSUE THREAD

**Issue by sivasadhu1** [SharePoint/PnP#1579]
I am getting one issue in sharepoint on-premise solution.

#### Category
[ ] Bug
[ ] Enhancement

#### Environment

[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Here i am passing the Language is 1033,1031

int[] languageIds={1033,1031};
  clientContext.Load(clientContext.Web, w => w.SupportedUILanguageIds);
                clientContext.ExecuteQueryRetry();

                for (int i = 0; i < languageIds.Length; i++)
                {
                    int languageId = languageIds[i];
                    if (languageId != LanguageHelper.DefaultLanguageId)
                    {
                        clientContext.Web.IsMultilingual = true;
                        clientContext.Web.AddSupportedUILanguage(languageId);
                        clientContext.Web.Update();
                        clientContext.ExecuteQueryRetry();
                    }
                }
But from above code i am getteg Error: Method not found: 'Void Microsoft.SharePoint.Client.Web.set_IsMultilingual(Boolean)

Can any one help me on this issue

**Comment by VesaJuvonen** [comment]
Hi sivasadhu1,
this means that in your environment or used CSOM assembly, there's no IsMultilingual property in the Web. There are differences of the CSOM APIs between SharePoint Online, 2016 and 2013. Not all properties are available especially in old 2013 versions. If you have at some point installed 2013 msi (SDK) with the client assemblies on your machine, you might run into this, eve though you would have reference on newer version of the CSOM assemblies as NuGet package.
