### ISSUE TITLE
Issue with Get-PnPProvisioningTemplate with workflows

### ISSUE THREAD

**Issue by PzKfWg** [SharePoint/PnP#1581]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
Latest release December 2016

#### Category
[X] Bug

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
I tried to export a template of a site with multiple complex SPD workflows (2010 and 2013 engine), but it did not work. I nailed down the issue to workflows with the switch "-Handlers Workflows". On the contrary, I could create the template with "-ExcludeHandlers Workflows". 

#### Observed Behavior
***From PowerShell:

> Get-PnPProvisioningTemplate -Out Workflows.xml -Handlers Workflows
> 
> Get-PnPProvisioningTemplate : hex 0x attendu dans '{0}'.  // "attendu dans" means "expected in"
> Au caractère Ligne:1 : 1
> + Get-PnPProvisioningTemplate -Out Workflows.xml -Handlers Workflows
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], FormatException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

***In the tracelog file:

> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	Code execution scope started	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	Base template available: STS0template	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	ProgressDelegate registered	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	MessagesDelegate registered	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7618	[Workflows]	[9]	[Debug]	Code execution scope started	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:07.5519	[OfficeDevPnP.Core]	[0]	[Information]	File d3e87945-5037-4806-9e89-590cfabc6b64.xaml saved to folder 	0ms	
> powershell.exe Information: 0 : 2017-01-05 14:45:07.5675	[Workflows]	[9]	[Debug]	Code execution scope ended	2799ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:07.5675	[Extraction]	[9]	[Debug]	Code execution scope ended	2814ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05

#### Steps to Reproduce
This is difficult to tell as there is a dozen of SPD workflows of multiple kinds and the tracelog does not seem to specify on which it stumbles. I can't find neither a list of known limitations in exporting workflows that could help nail down the issue.
Thank you for your attention!

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1015

**Comment by VesaJuvonen** [comment]
Since copied to PnP-Sites-Core repository, will close this one.

**Comment by mariagraziamerlo** [comment]
Hello. I've experience the same issue just today trying to export a site with complex 2010 and 2013 workflows in it. The following command was executed against a SharePoint 2013 On-Premises site:

Get-PnPProvisioningTemplate -Out E:\PnP\regs2.xml -Handlers Workflows  -SkipVersionCheck

The error was the following:
Get-PnPProvisioningTemplate : Expected hex 0x in '{0}'.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Out E:\PnP\regs.xml -Handlers Workflows  -SkipVersi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], FormatException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate
![error - export workflows]

![error - export workflows](https://cloud.githubusercontent.com/assets/16164321/24587356/627dbd20-17b5-11e7-8b56-b00f70260784.png)
