### ISSUE TITLE
Core.EmbedJavaScript.HeaderFooter suggestion 

### ISSUE THREAD

**Issue by levesquesamuel** [SharePoint/PnP#1582]
#### Category
[ ] Bug
[X ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[X ] SharePoint 2016
[X ] SharePoint 2013

#### Expected or Desired Behavior
As of now the title of this solution is a bit misleading. The title suggest that I would add a header and a footer. However, it's more about adding/removing breadcrumb & custom action and then behind the curtains a footer/header are added with a breadcrumb. I suggest to rename this sample and also to separate the different features inside the solution to something like this : 

- Add/Remove Header 
- Add/Remove Footer 
- Add/Remove BreadCrumb
- Add/Remove CustomActions Options

**Comment by aaclage** [comment]
Since i start with the project i can made the updates.

PS: The start of the sample was initially different (Breadcrumb) but just grown and in the end was Header & Footer, but with multiple extras...


Best regards, 
André Lage

**Comment by levesquesamuel** [comment]
Hi André, not sure if this is still relevant to update this project since the SPFx Extension now supports it : https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/js-application-listdrivenplaceholders
