### ISSUE TITLE
Azure service bus pre-requisites for a secure server

### ISSUE THREAD

**Issue by AnoojNair** [SharePoint/PnP#1583]
Hi,

I am using the **Provisioning.Hybrid.Simple** solution in order to provision sites on premise. We are facing challenges in communication between our secure server and azure service bus. What are the pre-requisites for using azure service bus for this solution.

What are the firewall changes we have to do , in order make this solution work?

**Comment by VesaJuvonen** [comment]
This slightly depends on the exact code setup, but following blog post contains nicely the needed ports to be open from the server towards Internet. It's also important to notice that these are outgoing ports, not incoming ports. https://blogs.msdn.microsoft.com/brunoterkaly/2012/02/07/azure-ports/
