### ISSUE TITLE
Issue with secondary lookup columns with Apply-PnPProvisioningTemplate

### ISSUE THREAD

**Issue by PzKfWg** [SharePoint/PnP#1586]
####Which PnP repository should you use to report the issue?####

    PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
    Latest release December 2016

Category

[X] Bug
Environment

[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Lookups with secondary columns should not have issues being provisioned. 

#### Observed Behavior
The script crashes when trying to provision secondary columns:

> powershell.exe Error: 0 : 2017-01-06 14:55:31.9112	[Fields]	[10]	[Error]	Updating field {2dc0ea51-1809-4fb9-b8b0-e0f9cd86dab0} failed: /sites/de/Lists/Formulaires : Value does not fall within the expected range.
> /sites/de/Documents partages : Value does not fall within the expected range.
>  :    à Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
>    à Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
>    à Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
>    à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.UpdateField(Web web, String fieldId, XElement templateFieldElement, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml)
>    à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	202334ms	c95c032a-b81b-41d1-8984-f5cacea20924

#### Steps to Reproduce
Here is the template generated by Get-PnPProvisioningTemplate used (rename to .xml). Notice that I put the secondary columns in the end of the Fields section (but just before the calculated fields). The main lookup column provisions correctly, but the first secondary column fails. I tried to change order and it is always the first secondary column that fails.
[DossierRH.txt](https://github.com/SharePoint/PnP/files/690758/DossierRH.txt)
Thank you for your hard work!

**Comment by PzKfWg** [comment]
Just realized that I ran into the same issue as [906](https://github.com/SharePoint/PnP/issues/906) so the error message makes sense, because if you look at the screenshot, no secondary column is selectable in the UI, so the script probably runs in the same issue.

**Comment by jansenbe** [comment]
I've been testing this and I'm able to provision a lookup field, including multiple columns as shown in below screenshot:
![image](https://cloud.githubusercontent.com/assets/7451219/22380222/ea452418-e4bc-11e6-8c23-bd53d14e521c.png)

This has been realized using the fields defined in this template: https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/field_add.xml

I'm closing this issue for now, if it's still not possible to correctly provision lookup fields using the approach mentioned above I would suggest to open a new issue, provide a clean repro and explain the used test environment.

**Comment by PzKfWg** [comment]
I notice that you used system columns as secondary columns while I used custom columns based on content types. I don't think that it is a fair test to use system column. I'll provide a simpler sample if I can. Thanks for checking this out, though!

**Comment by sebastianrogers** [comment]
I am also getting this with custom columns and lookups to custom lists, not the OOTB document library.

**Comment by rajajii** [comment]
I get this error only if additional lookup field already exist and i try to update it with pnp provisioning framework. No problem creating field for first time

**Comment by webtechy** [comment]
We are seeing this error. Anyone got a fix or workaround?
