### ISSUE TITLE
AspNetCore.Authentication bug creating url in SharePointContext.cs

### ISSUE THREAD

**Issue by IvanJosipovic** [SharePoint/PnP#1587]
#### Category
[X ] Bug
[ ] Enhancement

#### Expected or Desired Behavior
There is a bug in "AspNetCore.Authentication/src/OfficeDevPnP.Core.Framework.Authentication/SharePointContext.cs"

Line 382 "returnUrlBuilder.Query = queryNameValueCollection.ToString();" returns "System.Collections.Generic.Dictionary`2[System.String,Microsoft.Extensions.Primitives.StringValues]" as the code is running ToString() on a Key Value Pair.
This code should return a string with the format of Key1=Value1&Key2=Value2 etc...

**Comment by SharePointRadi** [comment]
Thanks for submitting this, I will definitely have a look at it ASAP.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
