### ISSUE TITLE
Change 'PnPnline' to 'PnPOnline' everywhere

### ISSUE THREAD

**Issue by jasonwusc** [SharePoint/PnP#1589]
#### Category
[X ] Bug

#### Environment
[X ] Office 365 / SharePoint Online

#### Corrective Action
'PnPnline' mispelling occurs twice within PnP/Solutions/Business.O365StarterIntranet/Deploy-Solution.ps1.
Replace all 'PnPnline with 'PnPOnline'. (Connect-PnPnline and Disconnect-PnPnline)

#### Root Cause
https://github.com/SharePoint/PnP/commit/217b0dec5443180c74db65bf57bdab91dada3473**

#### Expected or Desired Behavior
PowerShell file should no longer use 'Connect-PnPnline' or 'Disconnect-PnPnline'
PowerShell file should use 'Connect-PnPOnline' or 'Disconnect-PnPOnline'

Outstanding work! Greatly appreciative of PnP's efforts. 
-Jason Wiles
JasonW@AcceleraSolutions.com

**Comment by levesquesamuel** [comment]
This is my bad. I'll look into it.

**Comment by VesaJuvonen** [comment]
thx jasonwusc, fixed now to dev branch and will get to be released to master as part of the Feb release on 10th of Feb.
