### ISSUE TITLE
TaxonomyPicker support for loading the resources file via bundling

### ISSUE THREAD

**Issue by johnnycardy** [SharePoint/PnP#1593]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ x] SharePoint 2016
[ x] SharePoint 2013

If the main script (the taxonomypickercontrol.js) is loaded via a script bundle, then code to detect the scripts location and dynamically load the ".._resources.." file via ajax will fail.

The dynamic script loading mechanism for the resources should support both bundling and normal script loading methods.

**Comment by VesaJuvonen** [comment]
Closing this one, based on the PR you also submitted. Thx for sharing, appreciated.
