### ISSUE TITLE
NuGet Package Dependencies for SP2013

### ISSUE THREAD

**Issue by veebz** [SharePoint/PnP#1595]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
After installing the SharePointPnPCore2013 NuGet package, CSOM assemblies for SharePoint 2013 should be referenced.

#### Observed Behavior
SharePoint Online CSOM assemblies are referenced instead of SP2013 CSOM assemblies.  This is because the SharePointPnPCore2013 package has a dependency on AppForSharePointOnlineWebToolkit which in turn has a dependency on Microsoft.SharePointOnline.CSOM.  SharePointPnPCore2013 should have a dependency on AppForSharePointWebToolkit instead.

This issue leads to developers writing code against the wrong version of CSOM.

For instance, if you add the SharePointPnPCore2013 NuGet package and update all packages to the latest version, you can currently call the SystemUpdate method of a ListItem instance which is only available in SharePoint Online CSOM.  This code builds, but fails at runtime in a SharePoint 2013 environment.

#### Steps to Reproduce
Install the SharePointPnPCore2013 NuGet package.

**Comment by VesaJuvonen** [comment]
thx Matthew for sharing this. We'll have a look on this during this week and hopefully get it sorted out asap.

**Comment by jansenbe** [comment]
Hi Matthew,

The [SharePointPnPCore2013 nuget package](http://www.nuget.org/packages/SharePointPnPCore2013/) indeed has a dependency on AppForSharePointOnlineWebToolkit as you've noticed. We initially included that one to avoid the generation of sharepointcontext/tokenhelper when the pnp package was applied...this made that packages for online, 2013 and 2016 behaved the same. However now the AppForSharePointOnlineWebToolkit brings the Microsoft.SharePointOnline.CSOM nuget package in the latest releases, which off course if not what we want. We'll take this in account when we release our February 2017 release.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1016

**Comment by VesaJuvonen** [comment]
Since this relates on the PnP-Sites-Core, have moved issue to right repository. Closing this one and let's continue discussion in right repository. Like Bert mentioned, we are absolutely looking into addressing this with the next release.
