### ISSUE TITLE
Set-SPOProvisioningTemplateMetadata strips out the Providers tag from the provisioning template

### ISSUE THREAD

**Issue by JanVorster** [SharePoint/PnP#1599]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When using the Set-PnPProvisioningTemplateMetadata commandlet, I expect the Providers section to remain intact whilst the relevant attribute values are set on the Template xml.

#### Observed Behavior
When using the Set-PnPProvisioningTemplateMetadata commandlet, the Providers section is stripped out of the XML provisioning template file inside the .PNP file.

#### Steps to Reproduce
1) Extract a site temlpate using get-spoprovisioningtemplate
2) Add a <Providers> section (taken from the PnP\Samples\Provisioning.Extensibility) 
3) Set the template's Displayname using :
Set-PnPProvisioningTemplateMetadata -Path xxx.pnp -TemplateDisplayName "YYY"
4) Observe that the XML template file in the Files folder inside of the PNP file no longer contains the <Providers> section.

[Files.zip](https://github.com/SharePoint/PnP/files/747228/Files.zip)

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-PowerShell#737

**Comment by VesaJuvonen** [comment]
Hi JanVorster, Relocated to PnP-PowerShell repository. Closed from here to avoid issue getting missed.
