### ISSUE TITLE
Provisioning fails in the case additional admin cannot be resolved correctly through displayname

### ISSUE THREAD

**Issue by awdhaan** [SharePoint/PnP#1600]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4763.1000

#### Expected or Desired Behavior
The provisioning tool should resolve the value from the “Additional admins” field into actual users and apply this data when provisioning a site

#### Observed Behavior
When creating a site request via the request form and adding “Additional admins”, provisioning fails in case there is a user account entered from Active Directory (AD) for which another account exists in AD with the exact same display name (e.g. a production user and a test user), while the account name is unique. 
In that particular scenario, the remote timer job cannot resolve a unique user when reading the display name from the "Additional Admins" field in the "Site Requests" list on the host site collection. As a result, the site is not created and an exception occurs.

#### Steps to Reproduce
Ensure two AD users exist with the exact same display name and add either one of them to the “Additional Admins” field when requesting a new site to consistently reproduce the error.

### Possible solution
When changing the “ShowField” property from the “Additional admins” field from “Name” to “Account”, the code is able to resolve a unique user without running into the exception. For the installation, the PnPSiteProvisioning.xml for provisioning the Site Request list should be updated as follows:

<Field Type="User" Name="SP_AdditionalAdmins" DisplayName="Additional Admins" ID="{8c25e50c-9d31-483c-9a6d-66bdb39bbfe4}" Group="SiteProvisioning" Mult="TRUE" UserSelectionMode="0" ShowField="Name" Description="Additional Administrators" SourceID="{e39236f6-e0b6-4d25-99b4-6e02eceb2207}" StaticName="SP_AdditionalAdmins" AllowDeletion="TRUE" />

ShowField="ImnName" should become ShowField="Name".

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1051

**Comment by VesaJuvonen** [comment]
thx awdhaan, since this is directly related on the PnP Provisioning Engine, relocating this issue to PnP-Sites-Core, so that it's not getting lost.
