### ISSUE TITLE
Core.AppScriptPart Does not work with authenticated azure website

### ISSUE THREAD

**Issue by hittoday** [SharePoint/PnP#1621]
[ ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Please can the Core.AppScriptPart component https://github.com/SharePoint/PnP/tree/master/Samples/Core.AppScriptPart be made to work when it is hosted in an authenticated azure website. It is poor security to only allow it to work with anonymous access enabled websites. Currently anyone who knows the host name of the remote site can browse the javascript source files anonymously. This would fail a standard corporate security test.

#### Observed Behavior
The core.appscriptpart fails to work with an azure authenticated website and reports the below error in chrome.

![image](https://cloud.githubusercontent.com/assets/16746625/24075705/28184c16-0c18-11e7-93cf-c2a796aafb9c.png)

When anonymous access is enabled then the component works fine in all browsers tested.

#### Steps to Reproduce
Deploy the Core.AppScriptPart as a provider hosted add in to an azure website with azure authentication.
Deploy the appscript part to sharepoint online as normal
![image](https://cloud.githubusercontent.com/assets/16746625/24075689/e2e043ec-0c17-11e7-8eda-fbe87f76053d.png)

When you log in to the office 365 sharepoint site and the remoter provider site  allows anonymous requests the http trace can be seen below:

I have removed the host header of the dev site for security reasons.

Request URL:https://xxxx.azurewebsites.net/scripts/userprofileinformation.js
Request Method:GET
Status Code:200 OK (from disk cache)
Remote Address:51.140.180.76:443
Response Headers
Accept-Ranges:bytes
Content-Encoding:gzip
Content-Length:961
Content-Type:application/x-javascript
Date:Mon, 20 Mar 2017 09:28:38 GMT
ETag:"0572254199d21:0"
Last-Modified:Fri, 10 Mar 2017 01:53:42 GMT
Server:Microsoft-IIS/8.0
Vary:Accept-Encoding
X-Powered-By:ASP.NET
Request Headers
Provisional headers are shown
Referer:https://xxxxx.sharepoint.com/sites/dev/SitePages/DevHome.aspx
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

When you switch on app service authentication the trace is below

Request URL:https://xxxxx.azurewebsites.net/scripts/userprofileinformation.js
Request Method:GET
Status Code:302 Redirect
Remote Address:51.140.180.76:443
Response Headers
view source
Content-Length:544
Content-Type:text/html; charset=UTF-8
Date:Mon, 20 Mar 2017 09:43:12 GMT
Location:https://login.windows.net/5f098267-ecc3-4c10-9b0e-8ea4591ffa84/oauth2/authorize?response_type=id_token&redirect_uri=https%3A%2F%2Fxxxxx.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=0ecab9d5-85e3-45e6-97df-81176e8aa803&scope=openid+profile+email&response_mode=form_post&nonce=fb016c8dc49842d2a1ba5d8dd2cedc0b_20170320094813&state=redir%3D%252Fscripts%252Fuserprofileinformation.js
Server:Microsoft-IIS/8.0
Set-Cookie:Nonce=/SZUmnRu0jzRYsLsUgMtrS5ec7ptmrbWKn5H8Rrkn/kmjsZYuLEoypoXCW5mVY5TqMZOSFeKorAd7hPtnw6O3m+2JJ4ahWdMoOhJltPT7CYOW/9JU/fuXFboa9V1tCEY; path=/; secure; HttpOnly
X-Powered-By:ASP.NET
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Connection:keep-alive
Cookie:Nonce=KEZj2xyz9ep8If1WrQ6tZy0wPFp1XXFZie/ksksNBXW1phSREh5j9qxQpNgsaSD++Os1PqFKiUYtReyu/w0T1UGMx+TYGLwUB6YTcqq1feELQTyysi+uwEovKzvtVoG7; ARRAffinity=8178b3b2e8d11c3c178adca749545f846d9882b742e0df864a4df01a5d808af5
Host:xxxxx.azurewebsites.net
Referer:https://xxxxx.sharepoint.com/sites/dev/SitePages/DevHome.aspx
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

As we can see the azure authentication service is performing a redirect for authentication purposes thus causing the mimetype error

**Comment by VesaJuvonen** [comment]
Hi,
script works, if user has signed in to the site where it's hosted in Azure... challenge is not really in the solution as such, rather on the fact that SP Online and Azure uses different authentication model (for now). This means that anything hosted in Azure in secured ways, requires that user has signed in to that site or have sufficient permissions, even though user would have been signed in to SharePoint. If hosting scripts anonymously is a challenge for this deployment, you can always relocate the script for example to root site collection in the SharePoint online tenant... this way it would be secured, but easily accessible for customizations.

**Comment by hittoday** [comment]
many thanks for responding to my issue. Yes anything with anonymous would not cut it for me ever it would fail any standard corporate penetration test.

Moving forward a shared auth model for sp online and azure is definitely the right way forward - any timescale on this?

**Comment by VesaJuvonen** [comment]
There's no public timelines for the auth model changes. On the JS hosting - simple solution is to use SharePoint Online library for your use case. This way requests are authenticated and there's no concerns on getting JS files shared with externals.
