### ISSUE TITLE
Web.ApplyTheme times out in Modern Sites in SharePoint Online

### ISSUE THREAD

**Issue by michael-jensen** [SharePoint/PnP#1622]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Hi @VesaJuvonen I have followed the steps outlined in your [post on customizing modern sites](https://msdn.microsoft.com/en-us/pnp_articles/modern-experience-customizations-customize-sites) in an attempt to apply a theme programatically. I expect the method to apply the theme for the given spcolor file I've uploaded into the SiteAssets library.

#### Observed Behavior
When I attempt to apply a theme programatically, the ApplyTheme function times out every time (in Powershell or a console app).

#### Steps to Reproduce
1. Create a new O365 Group (either through the UI or programatically)
2. Create a Themes folder in the SiteAssets library in the modern site
3. Upload an spcolor file (go.spcolor) into that folder; I've used this spcolor file in other non-modern sites
4. Run the following CSOM code against that modern experience site:
```
var web = ctx.Web;
ctx.Load(web);
ctx.ExecuteQueryRetry();

var paletteUrl = $"{web.ServerRelativeUrl}/SiteAssets/Themes/go.spcolor";

ctx.RequestTimeout = Timeout.Infinite;
web.ApplyTheme(paletteUrl, null, null, true);
web.Update();
ctx.ExecuteQuery();
```

5. I routinely get a System.Net.WebException with the message: _The operation has timed out_. The amount of time it takes for the the timeout to occur varies, which I find a bit odd ... I've seen it occur in 180 seconds, and take as long as 365 seconds.

I have tried executing this code against numerous different modern experience sites, and they all behave the same way (timeout). I am able to change the theme in those sites through the UI (although it does take quite a while).

I have tried the following settings before executing the query, but I get the same result:

```
ctx.PendingRequest.RequestExecutor.RequestKeepAlive = false;
ctx.PendingRequest.RequestExecutor.WebRequest.KeepAlive = false;
ctx.PendingRequest.RequestExecutor.WebRequest.Timeout = Timeout.Infinite;
ctx.PendingRequest.RequestExecutor.WebRequest.ReadWriteTimeout = Timeout.Infinite;
System.Net.ServicePointManager.DefaultConnectionLimit = 200;
System.Net.ServicePointManager.MaxServicePointIdleTime = 2000;
System.Net.ServicePointManager.MaxServicePoints = 1000;
System.Net.ServicePointManager.SetTcpKeepAlive(false, 0, 0);
System.Net.ServicePointManager.DnsRefreshTimeout = Timeout.Infinite;
```

Do you have any any suggestions on why this continually times out, as I am able to apply the same theme to non-modern experience sites in my tenant?

Cheers
Mike

**Comment by VesaJuvonen** [comment]
This is unfortunately known issue around theme apply process with modern sites. Timeout happens in the call for the operation, but theme is eventually successfully applied to the site as long as you don't access the site for a while (if you access, there will be modification date exception). Unfortunately only short term solution is to apply the theme, wait a while and continue the provisioning process after that. Client call settings do not change the situation, since the server side timeout for the client side call is the meaningful one in this case. There is work being done on modern theming and branding, so this will be eventually changed / replaced with new branding capabilities.

**Comment by michael-jensen** [comment]
Thanks for the quick response @VesaJuvonen

**Comment by VesaJuvonen** [comment]
Closing, since unfortunately "as is".

**Comment by Zenexer** [comment]
@VesaJuvonen Does this explain the indefinite `Working on it...` screen that appears when attempting to change the theme through Site Settings?  Issue is described on [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/Office-365-Groups/Unable-to-Change-the-look-and-feel-for-Office-365-groups-site/td-p/52272).  Is the same workaround applicable?  I've waited quite a while on a brand new site without any luck.
