### ISSUE TITLE
SP.Peoplepicker blocks SP Function loadUserDataAsync(accountName, [RetValueName])

### ISSUE THREAD

**Issue by Thomas71735** [SharePoint/PnP#1623]
Hi folks,

in my SP App I am calling the function loadUserDataAsync various times to retrieve user data.

After the people picker returns some user data I want to get one more specific user property.

This time I get a "Microsoft.SharePoint.Client.InvalidClientQueryException". The error message says 

loadUserDataAsync failed: can not load user data

I am stuck and have no further ideas.

#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 2013 CU from 1.2017

#### Expected or Desired Behavior
loadUserDataAsync should return a result as it does when it is called before the Peoplepicker usage

#### Observed Behavior
This time I get a "Microsoft.SharePoint.Client.InvalidClientQueryException". The error message says 
loadUserDataAsync failed: can not load user data

#### Steps to Reproduce
My Code:
if ($('#peoplePickerDiv').spPeoplePicker('get')[0]) {
                var LoginName = $('#peoplePickerDiv').spPeoplePicker('get')[0].login;
                var UserName = $('#peoplePickerDiv').spPeoplePicker('get')[0].displayName;
                var EMail = $('#peoplePickerDiv').spPeoplePicker('get')[0].email;
                $('#peoplePickerDiv').spPeoplePicker("clear");
                //GetCurrentUserInfo("TRUMPF-shortName", function () {
                SP.SOD.executeFunc('userprofile', 'SP.UserProfiles.PeopleManager', function () {
                   // Async call is in here for a specific field "ShortName"
                  GetUserInfo(LoginName, "ShortName", function (ShortName) {
                    //var ShortName = "Dummy";
                   });
               });
}

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
