### ISSUE TITLE
Cannot complete this action.    Please try again.

### ISSUE THREAD

**Issue by nikunj231991** [SharePoint/PnP#1625]
An unhandled exception of type 'Microsoft.SharePoint.Client.ServerException' occurred in OfficeDevPnP.Core.dll

Additional information: Cannot complete this action.

Please try again.
![image](https://cloud.githubusercontent.com/assets/6532636/24299974/e20f6b74-10d0-11e7-8a33-527652a2d6b9.png)

why we are getting this error some times

**Comment by VesaJuvonen** [comment]
Hi @nikunj231991,
not sure on why this would happen, but having slightly more information on the environment could give some additional insights on what's actually happening. Is this on-premises or SharePoint Online. If that's on-premises, there could be some connectivity challenges, but hard to say. Have not seen this one personally in my work.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
