### ISSUE TITLE
ReuseTerm method is not updating the correct source term  in PnP Model

### ISSUE THREAD

**Issue by sdakhare** [SharePoint/PnP#1626]
I have created a term set in MMS as below -

**TermSetA** 
 - TermC   (remark - Term C is reused from TermSet B)
 - TermD   (remark - Term D is reused from TermSet B)

**TermsetB**
 - Term C 
   - Term D

So while creating the same term set hierarchy on another target Machine using PNP it is showing some thing different for **REUSED** Term as below  -

**TermSetA** 
 - TermC  
 - TermD   

**TermsetB**
 - Term C   (remark - It is showing Term C is reused from TermSet A in Member of Section of the Term )
   - Term D  (remark - It is showing Term D is reused from TermSet A in Member of Section of the Term)

Below is the code that I have used to create Reused Term on Target Machine -

 Term reusedTerm = targetTerm.TermStore.GetTerm(subSourceTerm.Id);
                    targetClientContext.Load(reusedTerm);
                    targetClientContext.ExecuteQuery();

                    Term childTargetTerm;
                    if (reusedTerm.ServerObjectIsNull.Value)
                    {
                        childTargetTerm = targetTerm.CreateTerm(subSourceTerm.Name, defaultLanguage, subSourceTerm.Id);
                        targetClientContext.Load(childTargetTerm, term => term.IsDeprecated,
                                                                  term => term.CustomProperties,
                                                                  term => term.LocalCustomProperties,
                                                                  term => term.IsSourceTerm);
                        targetClientContext.ExecuteQuery();
                        UpdateTerm(sourceClientContext, targetClientContext, subSourceTerm, childTargetTerm, languagesToProcess);
                    }
                    else
                    {
                        if (subSourceTerm.IsReused)
                        {
                            try
                            {
                                childTargetTerm = targetTerm.ReuseTerm(reusedTerm, false);
                                targetClientContext.Load(childTargetTerm);
                                targetClientContext.ExecuteQuery();
                           }
                            catch (Exception ex)
                            {
                                Console.WriteLine(ex.Message);
                             }
                        }

Please Suggest ???

**Category**

[ ] Bug

**Environment**

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

@VesaJuvonen

**Comment by VesaJuvonen** [comment]
Hi sdakhare, could you provide slightly more insights on the environment. Is this on-premises (which version) or SharePoint Online where the issue is happening? - This would help us to have sufficient amount of information for trying to reproduce the issue.  thx.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
