### ISSUE TITLE
TeamSiteSubSiteTemplate.xml is missing

### ISSUE THREAD

**Issue by KoenZomers** [SharePoint/PnP#1627]
####Which PnP repository should you use to report the issue?####
- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[X] Bug
[ ] Enhancement

#### Environment
N/A

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
https://github.com/SharePoint/PnP/blob/master/Solutions/Provisioning.UX.App/Provisioning.Job/Provisioning.Job.csproj describes that there should be a file Resources\SiteTemplates\ProvisioningTemplates\TeamSiteSubSiteTemplate.xml but it's not checked in to GitHub thus the project does not compile. See: https://github.com/SharePoint/PnP/tree/master/Solutions/Provisioning.UX.App/Provisioning.Job/Resources/SiteTemplates/ProvisioningTemplates

#### Observed Behavior
N/A

#### Steps to Reproduce
N/A

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
