### ISSUE TITLE
PnP Provisioning engine cannot retrieve default fields of list even if we changed the default field's title

### ISSUE THREAD

**Issue by calvinfeng5612** [SharePoint/PnP#1632]
####Which PnP repository should you use to report the issue?####
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
We expect to use PnP provisioning engine (CSOM code) to retrieve the default fields as well in order to keep all new sites consistent. Because sometimes the SP online developer may change the default field's title or something. But, I found from the code sample of PnP cannot / does not retrieve the default fields.

#### Observed Behavior
PnP provisioning engine sample cannot retrieve the default fields of a list.

#### Submission Guidelines
Reference on the sample and possibly code file: https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.Framework.Console

I would like to pop up this bug ASAP as I think the SP online developer may have the same issue of doing this. Please share your experience and code of how to fix this bug! Cheers

**Comment by VesaJuvonen** [comment]
Hi calvinfeng5612,
can you slightly more clarify what you mean with "default fields" in this context. Engine absolutely exports any fields set to default view or which have been added to the lists. Just to ensure that there is enough information for the community to provide fix fort this. thx.

**Comment by calvinfeng5612** [comment]
Hi Vesa, 
We are trying to retrieve everything except the content of a site source and apply to a new site. I see engine exports any added fields and default view or new views have been added to the lists. But, I can't see any value of default fields in the list of ProvisioningTemplate object when I debug my console application of PnP Engine. The reason I want to get those default fields is we manually changed the name of a default field from "Title" to "XXX" in the source template, rather than add new field. So, I want to know how to extract this kind of field by engine. Thanks

**Comment by VesaJuvonen** [comment]
thanks for the clarification and this indeed is not currently supported by the engine. We are obviously looking to have this capability potentially available in the future, but that depends on community contributions, like with any open source projects. This is though good feedback on the needed additional support.

**Comment by calvinfeng5612** [comment]
Hi Vesa,
Thank you for your reply and added highlighted labels. Hope the engine can handle the default fields soon. Please correct me if I'm wrong. I think the process of engine should be "Create" -> "Apply", which means the target site/ web part/ list must be created first, then do the apply procedure. So, I assume the engine does not extract default fields because every list has its default list when it being created. So, I think the idea of engine currently has good performance experience. Because we don't need to do the duplicate stuffs while applying the template. However, this is really a potential issue in the future.  
Cheers

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
