### ISSUE TITLE
The web template BICENTERSITE#0 is not available for sites on this tenant.

### ISSUE THREAD

**Issue by kavleen** [SharePoint/PnP#1633]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[*] Bug

#### Environment
[*] Office 365 / SharePoint Online

#### Expected or Desired Behavior
`SpoOperation _spoOperation = _tenant.CreateSite(_newsite);` should create business intelligence center with template id   BICenterSite#0.

#### Observed Behavior
Getting Error "The web template BICenterSite#0 is not available for sites on this tenant."

#### Steps to Reproduce
Please see attached image. 
PS: Renamed the tenant name and owner details for the sake of company policy.
![debugscreenshot](https://cloud.githubusercontent.com/assets/7964875/24596923/2581eb8e-1860-11e7-8e70-87343a503d81.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by longnlp** [comment]
Sharing the details, the business intelligence center template is only available for the user who has SharePoint Online Plan 2 license. more details is here: https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#feature-availability-across-office-365-plans
