### ISSUE TITLE
Want to create folder structure during console site creation

### ISSUE THREAD

**Issue by rkstarcass** [SharePoint/PnP#1638]
#### Category
[ ] Bug
[X ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Desired Behavior - Ability to copy the folder structure in a document library (This can include up to 2 levels of nested folders).  

#### Observed Behavior
Currently I am only able to copy all folders and have them created at the root of my new site.  The nesting is not maintained.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
