### ISSUE TITLE
Can't webpack PnP Starter Intranet for Office 365/SharePoint Online

### ISSUE THREAD

**Issue by jbarrar** [SharePoint/PnP#1645]
#### Category
[ x ] Bug
[ ] Enhancement

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

I was installing PnP Starter Intranet for Office 365/SharePoint Online by following the instructions in the md file. (https://github.com/SharePoint/PnP/tree/master/Solutions/Business.StarterIntranet).
When I reached the webpack step: "Check if everything is OK by running the "webpack" cmd from the ".\app" folder. You shouldn't see any errors here.", it should have not thrown any errors when the webpack command is run.

**Observed Behavior**

SharePointPnPPowerShellOnline version 2.14.1704.0 (April)
Node.js 6.10.2
webpack version: 1.14.0
typescript version: 2.2.0
sp-pnp-js version 1.0.6
Windows Server 2012 R2

The script starts with a message about ts-loader and then there are many "error TS2304: Cannot find name 'Promise'." error messages.

PS C:\projects\pnp-master\solutions\business.starterintranet\app> webpack
webpack : ts-loader: Using typescript@2.2.0 and C:\projects\pnp-master\solutions\business.starterintranet\app\tsconfig.json
At line:1 char:1
+ webpack
+ ~~~~~~~
    + CategoryInfo          : NotSpecified: (ts-loader: Usin...p\tsconfig.json:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Hash: 8c5c3c003d2e360e124e
Version: webpack 1.14.0
Time: 22687ms
                     Asset       Size  Chunks             Chunk Names
               layouts.css    1.07 kB       0  [emitted]  app
         ./img/spinner.gif  420 bytes          [emitted]  
   ./img/logo_intranet.png    16.8 kB          [emitted]  
./img/favicon_intranet.ico    1.15 kB          [emitted]  
                 js/app.js     622 kB       0  [emitted]  app
              js/vendor.js    1.48 MB       1  [emitted]  vendor
                portal.css    14.9 kB       0  [emitted]  app
         bootstrap-iso.css     134 kB       0  [emitted]  app
   ./img/default_image.png  762 bytes          [emitted]  
          layouts-edit.css  805 bytes       0  [emitted]  app
             js/app.js.map     715 kB       0  [emitted]  app
            portal.css.map  929 bytes       0  [emitted]  app
     bootstrap-iso.css.map     160 kB       0  [emitted]  app
           layouts.css.map  108 bytes       0  [emitted]  app
      layouts-edit.css.map  103 bytes       0  [emitted]  app
          js/vendor.js.map    1.73 MB       1  [emitted]  vendor
   [0] multi vendor 124 bytes {1} [built]
    + 292 hidden modules

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(10,31): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(14,36): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(20,39): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(26,38): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(32,41): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(38,41): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(54,45): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(60,42): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(65,28): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(72,73): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(78,40): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(85,54): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(91,46): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(97,57): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(102,32): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(106,27): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(112,55): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\userprofiles.d.ts
(118,37): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\site.d.ts
(31,23): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\site.d.ts
(37,51): error TS2304: Cannot find name 'Promise'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\sp-pnp-js\lib\sharepoint\rest\site.d.ts
(43,52): error TS2304: Cannot find name 'Promise'.

**It goes on and on like this... Farther down, some of these...**

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(39,27): error TS2304: Cannot find name 'IterableIterator'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(47,36): error TS2304: Cannot find name 'Iterable'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(226,38): error TS2304: Cannot find name 'IterableIterator'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(231,35): error TS2304: Cannot find name 'IterableIterator'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(236,37): error TS2304: Cannot find name 'IterableIterator'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(349,33): error TS2304: Cannot find name 'IterableIterator'.

ERROR in C:\projects\pnp-master\solutions\business.starterintranet\app\node_modules\@types\core-js\index.d.ts
(350,31): error TS2304: Cannot find name 'IterableIterator'.

**Comment by jbarrar** [comment]
I was able to reproduce the same errors on a Windows 10 PC.

![image](https://cloud.githubusercontent.com/assets/26453530/25021910/ddc4a976-2061-11e7-8b03-8c3f281fcf12.png)
![image](https://cloud.githubusercontent.com/assets/26453530/25021926/f42622b2-2061-11e7-94e0-a91b9f48c282.png)
![image](https://cloud.githubusercontent.com/assets/26453530/25021939/079d20ac-2062-11e7-9800-37a84bfccc98.png)
![image](https://cloud.githubusercontent.com/assets/26453530/25021959/15e64ae4-2062-11e7-8c01-e5e8a668621e.png)
![image](https://cloud.githubusercontent.com/assets/26453530/25021975/2596ea52-2062-11e7-88e7-9f00070ed8e4.png)

**Comment by jbarrar** [comment]
All of the ERROR lines went away when I changed a line in the tsconfig.json file from:
"lib": ["dom", "es5"]
to:
"lib": ["dom", "es5", "es2015"]
Should this be a permanent change for the package?

**Comment by VesaJuvonen** [comment]
This should be now fixed with the #1655 PR. Fix is available immediately in dev branch and merge to master early May.
