### ISSUE TITLE
each sample it asks for a login but does not accept a valid login

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/PnP#1647]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[ ] Bug
[ ] Enhancement
?
#### Environment
[ ] Office 365 / SharePoint Online
[X] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Run the samples with the initial login
#### Observed Behavior
For each sample it asks for a login but does not accept a valid login
#### Steps to Reproduce

go to /SharePointpnp-js-core/Pages/sampleviewer.aspx 
run any of the samples. it is stuck on the login

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
