### ISSUE TITLE
How to provision a custom WF on SharePoint Online while provisioning site collection

### ISSUE THREAD

**Issue by manojgudi2016** [SharePoint/PnP#1648]
####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
I am doing an analysis on Site collection provisioning, and would like to know how to provision custom workflows while provisioning a site collection on SharePoint Online.

#### Observed Behavior
I did find a resource on how to provision WF template on OnPremise and Dedicated Office 365.
https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.WorkflowTemplate
But can we use this solution to provision a WF template on SharePoint online?

Thanks to the PNP group for their support.
Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
