### ISSUE TITLE
Call to RER Failed with Authentication error.

### ISSUE THREAD

**Issue by VikramShityalkar** [SharePoint/PnP#1649]
- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Deployed [Sample Core.EventReceivers](https://github.com/SharePoint/PnP/tree/master/Samples/Core.EventReceivers) on Azure Web App service. The azure website is enabled with authentication (Azure Active Directory).
Added the Add-In  to site, this should trigger AppInstalled event.  
 
#### Observed Behavior
SharePoint add-in is failed to installed and detail section following error is recorded.

`The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer realm="xyz.azurewebsites.net"'. (xyz is replaced)
`
#### Steps to Reproduce
1. Deploy Web Application on Azure Web App service. 
2. Enable the Authentication / Authorization on Azure Web App service
3. Install Add-In on SharePoint site.
4. Observe errors for installation.

**Comment by VesaJuvonen** [comment]
This is by design, since SharePoint system account used to call your RER end point does have have an identity. This means that the model only works if endpoint is anonymous. Not optimal, but the current implementation of the RER model.

**Comment by MaheshakaMudli** [comment]
@VesaJuvonen : Do we have any changes in implementation for RER to incorporate the Azure AD authentication in RER.

**Comment by desaiprerak** [comment]
Hi @VesaJuvonen , Is there any alternative to for enabling RER with Azure AD authentication? Or would it required to use something else like Flow and Azure AD authenticated api/function app to have Azure AD authenticated calls from SharePoint?

**Comment by esutantya** [comment]
@VesaJuvonen we have security concern for enabling anonymous access. do you think its possible to put IP Restriction, to only allow SharePoint backend to call the RER ?
