### ISSUE TITLE
Existed DataRow will not be overwrited, but it will be duplicated

### ISSUE THREAD

**Issue by khha** [SharePoint/PnP#1650]
####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[V ] Bug
[ ] Enhancement

#### Environment
[V ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I am using O365 and created an xml templated file. In this template I add a new list item in the OOTB list "Tasks". When I run the powershell script the first time I see 1 list item in the tasks list. When I run it again I see the second. And so on so on. Is there a possiblity this list item will be over writed or maybe the whole list will be removed and created again?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
