### ISSUE TITLE
Open Workflow.Activities with Visual Studio 2015

### ISSUE THREAD

**Issue by fhunth** [SharePoint/PnP#1654]
https://github.com/SharePoint/PnP/blob/master/Samples/Workflow.Activities/Workflow.Activities.sln

#### Category
[] Bug
[x ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Open Solution on Visual Studio 2015

#### Observed Behavior
I cannot open this solution >>> https://github.com/SharePoint/PnP/blob/master/Samples/Workflow.Activities/Workflow.Activities.sln
on Visual Studio 2015
I get a message on Solution explorer that says "This project needs to be migrated"

#### Steps to Reproduce
Open Visual Studio Enterprise 2015

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
