### ISSUE TITLE
PnP Taxonomy Picker for Sharepoint Hosted Apps?

### ISSUE THREAD

**Issue by vimalpatel1826** [SharePoint/PnP#1658]
I have been looking into PnP Taxonomy Picker for provider hosted apps. I have prototyped PnP taxonomy picker similar but according to my requirement in a provider hosted app.  While researching and reading about it I come across few posts saying PnP Taxonomy Picker is only for / supported for provider hosted apps. Is this still true? I know we can use OOTB taxonomy picker for SharePoint hosted apps.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
