### ISSUE TITLE
Provisioning Existing site with selected SharePoint objects

### ISSUE THREAD

**Issue by harshasyamala** [SharePoint/PnP#1662]
Hello, 

I would like to know if there a way to update an existing sub site (with only few selected SharePoint Objects) using provisioning framework. We have this case for SharePoint Online and CSOM (with .NET) Provisioning.SubSiteCreationApp.

The scenario is something like this

1) We have created a site (of Team site type) with required settings like color theme, custom document library and folders in side the doc library.
e.g.
../doclib1/Testfolder1
.../doclib1/Testfolder2

2) Created custom site template of the above site and imported it to a new site collection

3) Using "Provisioning.SubSiteCreationApp" and site template we have created new sub sites (e.g. TestSiteCollection/SubSite1
TestSiteCollection/SubSite2

4) Now we have a requirement to update site (created in step#1), to add new folder in custom doc library
../doclib1/Testfolder3

Now the question here is, how to update the already created sub sites (SubSite1 and SubSite2) to have new folder (Testfolder3) ?

**Comment by braegelno5** [comment]
If you change your template and add there the new folder and use this on existing page again, the new folder is not there?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
