### ISSUE TITLE
Strange behavior when provisioning termstore navigation

### ISSUE THREAD

**Issue by Simon9552** [SharePoint/PnP#1664]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When you provision a site navigation to the sharepoint online termstore and you use resource files,
the termset should be updated or atleast completely overridden.

#### Observed Behavior
When you enter the name of the site navigation hard coded, the provisioning works fine. It seems to override the current present Site Navigation termset. Same counts for the terms. They get added fine when you hardcode them.

Example:
<pnp:TermSet Name="Site Navigation"  Description=""  IsAvailableForTagging="false">
<pnp:Term Name="Example" IsAvailableForTagging="false" SourceTermId="28e4cde5-9b12-4a1e-8dc3-8d94403218de">

In this case the existing site navigation is overridden. And terms are added.

When you use resource files in the Module.xml files. It tries to recreate but fails because the termset already exists. For the termset name and terms.

<pnp:TermSet Name="{res:SiteNav}"  Description=""  IsAvailableForTagging="false">
<pnp:Term Name="{res:NavDepartments}" IsAvailableForTagging="false" SourceTermId="28e4cde5-9b12-4a1e-8dc3-8d94403218de">

#### Steps to Reproduce
Deploy and activate a mananaged metadata navigation to the standard available termset for navigation.
Make use of a resource file. 

In a english environment the termset Site Navigation will be present. This is the one you should be trying to edit.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
