### ISSUE TITLE
angular 2 sharepoint REST

### ISSUE THREAD

**Issue by aminebench** [SharePoint/PnP#1666]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

Hello , i'm trying to get a list of data from SharePoint online 2013 using REST (http.get) . I've already setted permissions ( full controll ) from SharePoint. the problem that i'm facing the same error when running the service from app : Failed to load resource: the server responded with a status of 401 (Unauthorized) ... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 401.

can any one Help ?

**Comment by malexandrum** [comment]
In order to easily get data from SharePoint I would suggest you use the provided props.context.spHttpClient in order for it to handle sending the needed cookie and the X-RequestDigest needed for writing data.

**Comment by aminebench** [comment]
Hi , thank you for your response  , but in my case  i work on ANG2/Office365 apps so i use ADAL to perform authetification and provide  Token , i had settings the requirement acces for Office graph rather than SHarepoint online and grinting all nedded prmissions . So this is my code samples that return the error its a part of compnent service : 

const url="https://myorg.sharepoint.com/sites/ProgedPfe/_api/web/lists/getByTitle('Param_List')/items"
let headers = new Headers({ 'Authorization': 'Bearer ' + token ,"Accept": "application/json; odata=verbose",
         'Access-Control-Allow-Origin':'http://localhost:8080',});
    let options = new RequestOptions({ headers: headers });

        return this.http.get(url,options)
           .map((response: Response) => response.json()) ;

**Comment by malexandrum** [comment]
@aminebench That URL is SharePoint REST endpoint, not MS graph. The Access-Control-Allow-Origin needs to be set by your API, there's no effect if you set it on your call. 
Then, again, Sharepoint API doesn't allow CORS, so if you are on a different domain, it won't work. You either need to access Graph, or create a middleware (Azure Fubctions or AWS lambda) that doesn't need CORS.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
