### ISSUE TITLE
 Site Creation using PnP remote provisioning missing ability to pass contentdatabase parameter

### ISSUE THREAD

**Issue by reshmee011** [SharePoint/PnP#1669]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[ ] Enhancement

#### Environment
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Dec 2016 CU
#### Expected or Desired Behavior
We built a console app using the OfficeDevPnP.Core dll to provision site collections on SharePoint 2013 on premises environment.

We are planning to provision myriad of sites which will act as knowledge base for the company. It needs to be able to hold TB(s) of data.

Due to the limit of data that can be stored in a content database (200 GB), Ideally the site collection needs to be created using its own content database.

However the SiteCreationProperties is missing the property ContentDatabase which will allow to specify the content database the site collection will reside.

Can the SiteCreationProperties amended to include ContentDatabase? I guess it will be more a Microsoft level fix. 

Please advise.

#### Observed Behavior
Ability to specify content database when provisioning a site collection using the CreateSiteCollection method from TenantExtensions.cs

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Hi reshmee011,
this is unfortunately by design. PnP samples (https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.SiteCol.OnPrem) use CSOM/REST as remote operations for creating the site collection and database option is not exposed for the native CSOM, so it's not also exposed with PnP CSOM extension methods.
