### ISSUE TITLE
Notify graph to send only notifications failed to be processed

### ISSUE THREAD

**Issue by venkatesh-bhupathi** [SharePoint/PnP#1671]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
We see that Graph can include updates to multiple resources and send multiple notifications in single post to the Listen endpoint where as we see there is only one return status HttpStatusCode.OK or HttpStatusCode.BadRequest / InternalServerError.

In a scenario where we get 3 notification as part of single POST to the Notification endpoint, how do we need to handle if we are able process first 2 out of these 3 notifications and failed with 1 notification.

Is there a way to notify Graph that we failed to process 3rd notification and to re-send only the notification which we failed to process?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
