### ISSUE TITLE
DocumentPicker fails with "the collection has not been initialized"

### ISSUE THREAD

**Issue by rakoes** [SharePoint/PnP#1672]
Bug
SharePoint 2013
CU: 15.0.4701.1000 (March 2015)

Hi,

I was using the DocumentPicker control without any issues until I changed a field in a SharePoint list. The field changed from a 'Plain text' multiple lines of text field to an 'Enhanced rich text' field. In both cases the 'Append Changes to Existing Text' was selected. The odd thing is that this field does not live in the document library where the DocumentPicker is used on. 

When changed to an enhanced rich text field, i get this error in the asynchronous success handler function: "the collection has not been initialized" on line 78 of documentpickerdatasource.js. 

![image](https://user-images.githubusercontent.com/8904787/26879487-85db5736-4b91-11e7-9ae2-7ef7400e4162.png)

Switching the field back to a 'Plain text' field makes the error disappear again. Both lists are in the same web.

I hope someone can help.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
