### ISSUE TITLE
Deploy new mapped property in pnp:SearchSettings to existing sites

### ISSUE THREAD

**Issue by SusanYong123** [SharePoint/PnP#1674]
Hi All,
I am using Office 365 / SharePoint Online and I would like to add a new refiner mapped property and deploy them to multiple sites.

I tried to set the mapping through the Search Schema UI in one existing site (Site A) then I export the Search Configuration. From the exported xml file, I can see that the new refiner string mapping is there and I replace the SearchConfigurationSettings to my SearchSettings.xml file.

For applying this mapping to new site, I generate a SiteCollection xml which will be hosted in azure server by using this new SearchSettings.xml and tried to provision a new site. New site works perfect with all the new property mapping.

But for those existing sites, I need to applying the new property mapping there as well. I tried to push the SearchSettings.xml file but I keep getting some internal error. Normally for any new field in list or new content type, I just need to put the newly added part into the template.xml and deploy to existing site then the newly added part will be applied to that existing site. But this seem doesn't work for SearchSettings.

I am new to sharepoint online pnp, can someone please help? Basically what I need is to deploy the new property mapping for search configuration to multiple existing sites (do it programmatically instead of using Search Schema UI) thanks!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
