### ISSUE TITLE
Endpoint GetValidSiteUrlFromAlias has changed in functionality

### ISSUE THREAD

**Issue by JonasBjerke89** [SharePoint/PnP#1680]
Endpoint: GET /_api/GroupSiteManager/GetValidSiteUrlFromAlias?alias='aliastocheck' HTTP/1.1

As the documentation stated, it will return one of the following:
- Empty string - Alias cannot be used
- Full URL - Alias is good to be used

This has been working great for some time, but as of today when I call this endpoint, it will not return an empty string if the alias cannot be used, it returns a full URL but with an incremental number as suffix.

Example:
Alias request: Personal_MORT. There is already an Office 365 group with that alias.
Endpoint returns: https://tenant.sharepoint.com/sites/Personal_MORT2

You can see the result here:
![image](https://user-images.githubusercontent.com/21952399/27625620-85c87f26-5be5-11e7-87e9-9f0df7940314.png)

Any thoughts on this?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
