### ISSUE TITLE
"SharePointPnPCore2016" package - dependent dll package req

### ISSUE THREAD

**Issue by shinsgit** [SharePoint/PnP#1682]
Hello,
I am trying to add "SharePointPnPCore2016" package from NuGet Package Manager but I get this error:
Failed to add reference. The package 'SharePointPnPCore2016' tried to add a framework reference to 'Microsoft.Office.Client.Policy, Version=16.0.0.0' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance. Error HRESULT E_FAIL has been returned from a call to a COM component.
The application where I am trying to add this package is using .Net Framework 4.5.2.

I realized that after installing all the dlls (mentioned below) from NuGet, it let me install "SharePointPnPCore2016" package.

•	Microsoft.Office.Client.Policy
•	'Microsoft.Office.Client.TranslationServices, Version=16.0.0.0' 
•	'Microsoft.SharePoint.Client, Version=16.0.0.0'
•	'Microsoft.SharePoint.Client.DocumentManagement, Version=16.0.0.0'
•	'Microsoft.SharePoint.Client.Publishing, Version=16.0.0.0' 
•	Microsoft.SharePoint.Client.Search, Version=16.0.0.0'
•	'Microsoft.SharePoint.Client.Search.Applications, Version=16.0.0.0' 
•	'Microsoft.SharePoint.Client.Runtime, Version=16.0.0.0' 
•	'Microsoft.SharePoint.Client.Taxonomy, Version=16.0.0.0'
•	'Microsoft.SharePoint.Client.UserProfiles, Version=16.0.0.0' 
•	'Microsoft.SharePoint.Client.WorkflowServices, Version=16.0.0.0'

Is there way to bundle all the dlls in a package and that can be installed with the actual SharePointPnPCore2016 package itself? This way it will save us a lot of effort.
If there exists something like this already, can you please let me know.

Thanks in advance
.

**Comment by braegelno5** [comment]
May be the dependcy window for this installs was in the background, or ..?

**Comment by shinsgit** [comment]
No it did not install any dependency in the background. But I realized that I had to explicitly install "SharePointPnPCoreOnline" which I guess is alternative to "OfficeDevPnPCore16". OfficeDevPnPCore16 shows as deprecated.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by ThreadPitt** [comment]
Well, I have exactly the same issue here with the current package: **2.27.1806 on Windows 8.1, VS 2017**

Error		Failed to add reference. The package 'SharePointPnPCore2016' tried to add a framework reference to 'Microsoft.Office.Client.Policy, Version=16.0.0.0' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.			0

**Comment by bookworm2death** [comment]
This is also an issue on SharePointPnPCore2013 v3.2.1810. After installing all the packages shinsgit mentions I was able to install it.

**Comment by ken-hansen-rga** [comment]
Here's what I found. The latest version of all the dependencies on Nuget is 15.0.0.0, some of the package names have changed from Microsoft.SharePoint.Client.... to SharePoint.Client....

Here's my quick script:
```bash
$pkgNames = @("Microsoft.Office.Client.Policy","Microsoft.Office.Client.TranslationServices","Microsoft.SharePoint.Client", "Microsoft.SharePoint.Client.DocumentManagement", "SharePoint.Client.Publishing", "SharePoint.Client.Search", "SharePoint.Client.Search.Applications", "Microsoft.SharePoint.Client.Runtime", "SharePoint.Client.Taxonomy", "SharePoint.Client.UserProfiles", "SharePoint.Client.WorkflowServices", "SharePointPnPCore2016")

$pkgNames | % { Install-Package $_ -Version 15.0.0.0 }
```
