### ISSUE TITLE
HTTP Error 403.14 - Forbidden when launching Samples/Branding.AlternateCSSAndSiteLogo

### ISSUE THREAD

**Issue by adamcoulombe** [SharePoint/PnP#1686]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
It should run like in the video @ https://channel9.msdn.com/Blogs/Office-365-Dev/Alternate-CSS-and-set-site-logo-Office-365-Developer-Patterns-and-Practices

#### Observed Behavior
It launches a window with an HTTP Error 
![image](https://user-images.githubusercontent.com/469038/29173656-075830fc-7db2-11e7-96c5-1b748c2eb0fb.png)

#### Steps to Reproduce
I installed Visual Studio community with the Sharepoint development bundle. When I tried to run PnP/Samples/Branding.AlternateCSSAndSiteLogo, it didnt launch - see screenshot above

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
