### ISSUE TITLE
"Sideloading  of apps is not enabled on this site" when running Samples/Core. EmbedJavascript

### ISSUE THREAD

**Issue by adamcoulombe** [SharePoint/PnP#1687]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
It should run as per the video # https://channel9.msdn.com/Blogs/Office-365-Dev/JavaScript-injection-in-SharePoint-Online-Office-365-Developer-Patterns-and-Practices

#### Observed Behavior
It doesnt run correctly. I get the following error:
```
2>Error occurred in deployment step 'Install SharePoint Add-in': Sideloading of apps is not enabled on this site.
``` 
![image](https://user-images.githubusercontent.com/469038/29174391-2e6937d4-7db4-11e7-83ca-bf85d123032f.png)

#### Steps to Reproduce
I installed visual studio with the Sharepoint development bundle, opened the  Core. EmbedJavascript solution, configured with my site url, then pressed "Start"

**Comment by jasonkatz424** [comment]
You need to create a sharepoint developer side.  Creating a new sharepoint developer site is the same as creating any other sharepoint site, but you just click on developer for site type.  Also, you will need to package the app and upload it to the app catalog site.

**Comment by VesaJuvonen** [comment]
seems that @jasonkatz424 already processed this - thx. The sample is designed to demonstrate used APIs and doing F5 in VS only works with dev site collections. In production usage, you'd set these APIs using either remote provisioning solution, app installation event or using PnP PowerShell. The objective of this sample is to show the concept and development experience.
