### ISSUE TITLE
Error performing user search : Access denied. You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by ShujaathKhan** [SharePoint/PnP#1692]
When ever trying to do the search for user, just end-up getting alert as **Error performing user search**
and get detailed server error as mentioned in the screenshot.

-  It was working fine when was implemented for first time.
- This is happening when trying to run applcation using the SPAdministrator login which is the admin accont for the given developer site.
attached screenshot for complete detailed ref.

![image](https://user-images.githubusercontent.com/10792780/29817411-8602d1aa-8cd5-11e7-980d-b3a9cdbbded9.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
