### ISSUE TITLE
ECM.MVCTaxonomyPicker loose user selected terms once the form is posted to server and model state is not valid

### ISSUE THREAD

**Issue by khannsh** [SharePoint/PnP#1693]
ECM.MVCTaxonomyPicker loose user selected terms on view reloaded in the case of Model state is invalid when the form is posted to server.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
