### ISSUE TITLE
PnP Starter Intranet 2.0 licence violation

### ISSUE THREAD

**Issue by alirobe** [SharePoint/PnP#1700]
/Solutions/Business.StarterIntranet/app/src/styles/css/fonts 

Contains a proprietary font - Myriad Pro - which is Adobe IP, and should not be made publicly available in an open source repository.

Nice work on the rest of it though 👍 @FranckyC

**Comment by alirobe** [comment]
@FranckyC 
a mention
 for the attention
of a frenchman

**Comment by FranckyC** [comment]
Hi @alirobe, nice catch.

I thought the Regular font will be fine but apparently not. I will fix this as soon as possible. 
Thank you for your feedback.

**Comment by alirobe** [comment]
No worries. Voice of experience, been bit by that font before myself.

**Comment by FranckyC** [comment]
@VesaJuvonen You can close this one. Resolved.

**Comment by VesaJuvonen** [comment]
Closing.
