### ISSUE TITLE
Adding Document Library and List Web Parts in modern page using c# csom

### ISSUE THREAD

**Issue by MunojKannan** [SharePoint/PnP#1702]
Hi all, 

   I`m trying to add Document Library and List Web Parts in the modern pages. I`m trying to add the listviewwebparts using the below code taken from the [(https://msdn.microsoft.com/en-us/pnp_articles/modern-experience-customizations-customize-pages)]

**ClientSidePage page = ClientSidePage.Load(context, pageTitle);
var webp = page .InstantiateDefaultWebPart(DefaultClientSideWebParts.List);**

But the above code adds only the list preview. After that we should edit the page and have to select the necessary list from the preview manually to act as a list view web part. 
By manual adding the same procedure is followed, that the list preview is shown and from the preview we have to select the specific list to act as list view web part.
We have to add the list view web part in modern pages programmatically.
Is there any way to overcome this problem? please suggest.

Thanks in Advance

**Comment by jansenbe** [comment]
You need to specify the web part properties json data. Would recommend checking out the latest web cast on this topic: https://www.youtube.com/watch?v=0ELZ_OLmCbE&t=490s as it shows how to grab the properties of a configured web part. 

List web part is a special case and we added some additional logic in the dev branch (so not yet in published version) that allows you specify the list title in the json metadata which then will be "completed" with the actual list id and url. Check out this PR to learn more abour that change: https://github.com/SharePoint/PnP-Sites-Core/pull/1335

**Comment by MunojKannan** [comment]
@jansenbe  thanks for the update. "(so not yet in published version)" do you have any idea about when this  version will be released? Please let me know

Thanks in Advance.

**Comment by jansenbe** [comment]
That change is the current version, see https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Utilities/CanvasControl/Processors/ListControlPostProcessor.cs
