### ISSUE TITLE
Reporting Bug in Core.ListViewThreshold code while using camlQuery.FolderServerRelativeUrl property

### ISSUE THREAD

**Issue by sachinbiskop** [SharePoint/PnP#1703]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

https://github.com/SharePoint/PnP/blob/master/Samples/Core.ListViewThreshold/Core.ListViewThreshold/Program.cs

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
I am trying to retrieve files from a specific document library folder(with RecursiveAll view option) using "GetListItemsByBatch()" method in the above mentioned code file. The document library am using is having more than 40000 files/folders and folder specific folder which am querying is at 4th to 5th level hierarchy and contains very few files. 

So while using the above code to retrieve files from specific folder I set the camlQuery.FolderServerRelativeUrl = "/sites/site1/Doclibrary/Folder1/Folder2/Folder3/Folder4/Folder5";

When i executed the code i got Error "The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator".

when i executed the same code without the "FolderServerRelativeUrl" property, I am able to retrieve all the 40000 files from document library. 

#### Observed Behavior
Not able to retrieve files/folders from a specific folder at 4th or 5th level hierarchy in document library which is having more than 40000 files/folders.

#### Steps to Reproduce
Execute the "GetListItemsByBatch()" method on a document library which is having more than 5000 or 20000 files/folders and set the property camlQuery.FolderServerRelativeUrl to point to specific folder at 4th or 5th level. Please note that, View scope should be set to Recursive All.PFB
          
           //Set View Scope for the Query
            camlQuery.SetViewAttribute(QueryScope.RecursiveAll);

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
