### ISSUE TITLE
PnP Core Core.UserProfiles.Sync caching ?

### ISSUE THREAD

**Issue by dgrooms** [SharePoint/PnP#1704]
I'm seeing an issue where we edit a property in an on -premise AD that is then synced to Azure AD.
We've verified that the value does propagate to the Azure AD.

When we run the UserProfiles.Sync application the value read from the item is the old value before editing even though over an hour has passed and we know at least the sync from on prem to Azure has happened.

Are there any other caches involved and is there anything I should do in order to ensure the values read from the Graph Api are current and not stale copies ?

Thanks,

Dave

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
