### ISSUE TITLE
Struggeling with Microsoft.SharePoint.Client.Site.Classification - Update is only valid for a short time 

### ISSUE THREAD

**Issue by mmsharepoint** [SharePoint/PnP#1705]
#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

Was directed here by @mcmynn83 
#### Expected or Desired Behavior
Setting programmatically Microsoft.SharePoint.Client.Site.Classification to a value, that value gets persisted as long as it is not changed and displayed in modern experience site below the Site Title as shown in Vesa's PnP Short Video. https://www.youtube.com/watch?v=E-8Z2ggHcS0&list=PLR9nK3mnD-OXZbEvTEPxzIOMGXj_aZKJG

#### Observed Behavior
When I set the update, the value takes effect and is shown. But after a while, maybe forced by reopening the browser or what ever it disappears in the UI and a check via code assures that the value is empty.
Looks like it's overwritten from 'somewhere'?

#### Steps to Reproduce
Configure your tenant like mentioned by Vesa in above's PnP Short video OR skip this step (doesn't matter for my result)
Use PnP Powershell or CSOM (code / PS) to set the value to one you like (is a pre-configured entry from procedure above or not, doesn't matter) to update that setting:
$site = $clientContext.Site
$clientContext.Load($site)
$clientContext.ExecuteQuery()
$site.Classification = "Non-Confidential"
$clientContext.ExecuteQuery()
OR
Connect-PnPOnline -Url $siteUrl -Credentials $credentials
$site = Get-PnPSite
Get-PnPProperty -ClientObject $site -Property "Classification"
$site.Classification = "New Test"
Execute-PnPQuery
I checked several options but did not find a solution. Am I missing something or is there a bug?
Setting the value via UI indeed "lasts forever" but we have an automatic provisioning solution in place here ;-)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
