### ISSUE TITLE
ObjectNotFound: (C:\Business.StarterIntranet\app\dist:String) [Push-Location]

### ISSUE THREAD

**Issue by johnbrice** [SharePoint/PnP#1706]
Unable to locate dist folder in solution after downloading. Pretty sure this was there in previous versions.

**Comment by FranckyC** [comment]
Hi @johnbrice, try to remove the dist folder and then run the "webpack" cmd again. This folder is not included in the repository, it is an auto generated folder.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
