### ISSUE TITLE
PnP Timer Job - OnPremise Connectivity - TimerJob Run Method is not getting called

### ISSUE THREAD

**Issue by bhanuchintha** [SharePoint/PnP#1707]
#### Expected or Desired Behavior
Have written a TimerJob based on PnP Framework and tried to connect to the SP 2013 On-Premise site. 
 
https://msdn.microsoft.com/en-us/pnp_articles/timerjob-framework
 
I have used the below authentication and should be able to connect to OnPrem site and Run job has to be executed.
 
public void UseNetworkCredentialsAuthentication(string samAccountName, string password, string domain)
 
The same job is working fine if i tried to connect to SP Online and use the below authentication -
 
public void UseOffice365Authentication(string userUPN, string password)

#### Observed Behavior
The issue i am getting is - TimerJob Run method is not getting executed and i do not see exception/error here - for OnPremise site

#### Steps to Reproduce
https://techcommunity.microsoft.com/t5/Office-365/PnP-Timer-Job-OnPremise-Connectivity-Run-Method-Call/m-p/107730#M5518

#### Category
[ ] Bug

#### Environment
[ ] SharePoint 2013

####Sample Code that i have written -
class Program
{
static void Main(string[] args)
{
Class1 job = new Class1();
job.AddSite("https://OnPremSiteURL");
job.UseNetworkCredentialsAuthentication("username", "password", "domain");
job.Run();
}
}
 
class Class1 : TimerJob
{
public Class1() : base("CustomListArchivalJob")
{
TimerJobRun += Class1_TimerJobRun;
ManageState = true;
}
private void Class1_TimerJobRun(object sender, TimerJobRunEventArgs e)
{
}
}

**Comment by bhanuchintha** [comment]
I used the PnP SP 2013 nugget package here and it worked fine.

But, I still doubt why the latest package do not work with SP 2013 when it has provided methods to connect to On-Premise environment. Is this a bug?
 
Thanks & Regards,
Bhanu

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
