### ISSUE TITLE
Provisioning.ModernPages sample cannot find webpart by name

### ISSUE THREAD

**Issue by kath561** [SharePoint/PnP#1708]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
sample works

#### Observed Behavior
sample fails at line 39 as AvailableClientSideComponents returns a guid in name field not the name text needed for this code to work

#### Steps to Reproduce
run sample down to line 39 and inspect returned components object. Name property contains a guid.
38                                 var components = p.AvailableClientSideComponents(); 
39                                 var myWebPart = components.Where(s => s.Name == "HelloWorld").FirstOrDefault(); 
40                                 if (myWebPart != null) 

Guid problem has been raised as a separate issue against AvailableClientSideComponents.

Sharing is caring.

**Comment by jansenbe** [comment]
Closing this one, there has been a discussion about this in sites core repo.
