### ISSUE TITLE
SharePoint Authentication fails - Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by alexmoraru25** [SharePoint/PnP#1709]
I have the following error when running the StarterWeb project:

Microsoft.AspNetCore.Server.Kestrel[0]
ConnectionFilter.OnConnection
System.AggregateException: One or more error occurred. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

![image](https://user-images.githubusercontent.com/9262373/31066432-9b45463e-a755-11e7-88df-1752ebaf859d.png)

![image](https://user-images.githubusercontent.com/9262373/31066442-aa0e1a42-a755-11e7-876a-b51f9aad5663.png)

- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
