### ISSUE TITLE
Add webpart to modern page

### ISSUE THREAD

**Issue by LudwigVanGysel** [SharePoint/PnP#1710]
I am trying to add a webpart to a modern page using the ClientSidePage and ClientSideWebPart class. I'm able to create pages however adding web parts does not seem to work. The debugger gets stuck at the last line in the code below. I retrieved this code from the sample available in the GitHub repository.

I'm able to retrieve the web title so my context seems to be correct. Anyone has an idea what could be wrong?

```
using (var context = new AuthenticationManager().GetSharePointOnlineAuthenticatedContextTenant(
            $"{tenantUrl}{tenantRelativeUrl}",
               "user",
               "password"))
           {
              var page2 = context.Web.AddClientSidePage("PageWithSections.aspx", true);
               page2.AddSection(CanvasSectionTemplate.ThreeColumn, 5);
               page2.AddSection(CanvasSectionTemplate.TwoColumn, 10);
               var componentsToAdd = page2.AvailableClientSideComponents();
            }
```

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Add the webpart to the page.

#### Observed Behavior
Can't retrieve the available web parts or add a web part to a page.

**Comment by LudwigVanGysel** [comment]
I was able to isolate the issue to the line below in the GetClientSideWebPartsAsync method.

`HttpResponseMessage response = await httpClient.SendAsync(request);`

This works in a console application but not in an ASP.NET MVC controller action due to threading. Could this be made compatible?

**Comment by jansenbe** [comment]
I've made some changes to the async logic in sites core, which hopefully will fix your problem. Please try again once the October release becomes available, which should be next week Monday. Closing this issue for now, but don't hesitate to re-open if needed.
