### ISSUE TITLE
PnP Starter Intranet 2.0 - Search result breadcrumbs not displaying properly

### ISSUE THREAD

**Issue by jbarrar** [SharePoint/PnP#1711]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Search pages are expected to have breadcrumbs showing "home" and "search" as the current location or even better, no breadcrumb row at all.

#### Observed Behavior
When searches are performed, regardless of the choice of intranet, document or people, there is an error message when displaying the breadcrumbs. 

> Unable to determine the site map position for this page. Ensure you have filled the "Site Map Position" field for this page or set this page as target url for a term in the site map.

#### Steps to Reproduce
After a clean install of the StarterIntranet project, the following default column values were set as the instructions detailed:
`Library/Folder    Column    Value `
`Pages/   Content Type    Page `
`Pages/News    Content Type    News `
`Pages/News    Site Map Position    News `
`Pages/Events  Content Type    Event `
`Pages/Events  Site Map Position    Event (?? News ??) `
`Documents/    Content Type    Document `

The Site Map Position for Pages/Events was set to News because there is no Event Site Map Position. This may be a separate issue and I realize there is full ability to create new menus with the Site Map settings in the Term Store.
Searching any topic brings up a search page that reports the error of not being able to determine the site map position.

#### Workaround Solution:
If the Pages/Search.aspx item is edited from Site Contents through the Properties context menu, Site Map Position is not displayed for editing. If the Search Results page is edited using the "Edit Page" drop-down under settings, the Site Map Position field is exposed. If it is set there to something like "Sites" and the page saved and published, the breadcrumb function will work, albeit showing the search page as being in "Sites". A Site Map position could be named in such a way that it wouldn't be odd to have searches show there, but ideally there would be no breadcrumb row on a search page, as the home button is available right above in the header.

Interested in your feedback, as I'm curious if I simply set something up incorrectly.

![intranet search error](https://user-images.githubusercontent.com/26453530/31324833-ca04c984-ac84-11e7-8bb0-22010a41b707.JPG)
![intranet search edit page](https://user-images.githubusercontent.com/26453530/31324836-d00a9d9a-ac84-11e7-9001-a81a85f97445.JPG)
![intranet search workaround](https://user-images.githubusercontent.com/26453530/31324840-d42b1044-ac84-11e7-8cf4-d099160edc3e.JPG)

**Comment by jbarrar** [comment]
I noticed that the demo pictures have "Search" as a Term that shows up in the main link bar. If that's the solution, it might be worth integrating it into the code so that it operates that way out of the box.

**Comment by FranckyC** [comment]
Hi @jbarrar,

This behavior is by default. In the solution, the search page is a "_Static page_". All static pages have a field called "_Site Map Position_" accessible through the page layout and indicates where the page goes in the global navigation. It is up to you to fill this information according to your context. For instance, you can create a term "Search" (or any other meaningful term) in the navigation term set (Site Map EN/FR) and link it to the page via this specific field. Also, don't forget to set the term URL pointing to your physical page.

All this behavior is explained in details in the official [documentation ](https://transactions.sendowl.com/packages/48364/D024B326/view)btw.

Maybe the message is misleading and should be a warning instead of an error because it's not.

**Comment by jbarrar** [comment]
Thank you for the response. I guess this makes sense, as it's clear in the post-installation steps that setting up page context is the responsibility of the implementer. Perhaps just a note about it in the Readme.md where the site map position setup is discussed would clarify this for future users. The project is amazing and in a perfect world, I'd buy the documentation to support the cause. For now I can offer my thanks for providing a valuable resource.

**Comment by FranckyC** [comment]
Thank you for your feedback @jbarrar!
