### ISSUE TITLE
Remote Provisioning Role Assignments huge time difference in comparison to PowerShell

### ISSUE THREAD

**Issue by CPSTech** [SharePoint/PnP#1712]
Hi All,

Need some advice.

When trying to provision 3 security groups with role assignment on a sub-site on a site collection with around 10k security/SharePoint groups it is taking 46mins to complete, whereas using PowerShell the process takes around 14sec. This was tested on a vanilla SharePoint Online environment, both using the same xml file. It was also concluded that the quantity of Security/SharePoint groups have a direct correlation on the provisioning time while using the remote provisioning but doesn't impact PowerShell.

Can anyone explain why there is such a big difference while using Remote Provisioning compared to using PowerShell?

Attached technical information.
 XML: [PermUpdateTemplate.txt](https://github.com/SharePoint/PnP/files/1367994/PermUpdateTemplate.txt)

Results using provisioning: 2781077ms / 46min
 2017-10-03 15:15:12.2021 [Site Security] [27] [Debug] Code execution scope started 0ms b768b099-01d7-49ef-ba72-5b7a8ce3813f
 2017-10-03 16:01:31.8529 [Site Security] [27] [Debug] Code execution scope ended 2781077ms	b768b099-01d7-49ef-ba72-5b7a8ce3813f

Results using PowerShell: 14045ms / 14sec
 PowerShell_ISE.exe Information: 0 : 2017-10-03 16:11:24.5048 [Site Security] [12] [Debug] Code execution scope started 0ms e3b4d80d-1e84-440c-ad95-a01670de7b35
 PowerShell_ISE.exe Information: 0 : 2017-10-03 16:11:38.5478 [Site Security] [12] [Debug] Code execution scope ended 14045ms	e3b4d80d-1e84-440c-ad95-a01670de7b35

May the PnP be with you!

Thanks,

CPS Tech

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
