### ISSUE TITLE
List Information report/document

### ISSUE THREAD

**Issue by fhunth** [SharePoint/PnP#1713]
Is there something (plugin/powershell command/code/whatever) to generate a list report/document that shows all fields, types, details for a given list?

#### Category
[ ] Bug
[X] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[x ] SharePoint 2016
[x ] SharePoint 2013

#### Expected or Desired Behavior
Generate a report with all list settings

**Comment by gitzimm** [comment]
Are you looking for something like this?
It's something I have been working on and maybe I could create a repo to share it.

[](https://youtu.be/khSTbunHO84)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
