### ISSUE TITLE
Using MVC Webapp as client in AzureAD.WebAPI.SPOnline sample

### ISSUE THREAD

**Issue by AnassKartit** [SharePoint/PnP#1716]
Hi,
Can you please explain the steps required to replace the Client in the sample with an MVC web application and being able to get the user documents displayed in the app, especially the token part.
 

#### Category
[ ] Bug
[ x] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

 
#### Expected or Desired Behavior
Be able to display user documents in an MVC protected with Azure AD that calls webapi (on behalf of) flow.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
_Login to the MVC app using the user credentials, getting the user documents displayed in the portal.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
