### ISSUE TITLE
Business Starter Intranet install

### ISSUE THREAD

**Issue by johnbrice** [SharePoint/PnP#1717]
Installed the business starter intranet, with no issues.

However, when navigating to the site the page has not been configured and doesnt show any web parts. I used the switch -prod and -inludedata.

Has anyone experienced this before? previous versions have worked fine.

**Comment by FranckyC** [comment]
HI @johnbrice, can you provide a quick screenshot of your home page? Also, what version of SharePoint do you use ?

**Comment by hellblazeruk** [comment]
Hi,

SharePoint online.

Regards,
Alex

Sent from my iPad

On 23 Oct 2017, at 15:55, Franck Cornu <notifications@github.com<mailto:notifications@github.com>> wrote:


HI @johnbrice<https://github.com/johnbrice>, can you provide a quick screenshot of your home page? Also, what version of SharePoint do you use ?

**Comment by FranckyC** [comment]
HI  @johnbrice. Can you retry with a new site collection? Make sure this is a publishing site.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
