### ISSUE TITLE
Can't create Communication site with app only access

### ISSUE THREAD

**Issue by Maksim-Ilyenia** [SharePoint/PnP#1731]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Expected or Desired Behavior

 I try to create communication site with certificate app only access. I have 200 OK response and 
`{
	"d": {
		"Create": {
			"__metadata": {
				"type": "SP.Publishing.CommunicationSiteCreationResponse"
			},
			"SiteStatus": 3,
			"SiteUrl": ""
		}
	}
}

My code below:

var clientContext = new OfficeDevPnP.Core.AuthenticationManager().GetAzureADAppOnlyAuthenticatedContext(tenantId, clientId, certificate, siteUrl);
    var siteCreationProperties = new CommunicationSiteCollectionCreationInformation
    {
      Url = "https://myTenant.sharepoint.com/sites/commsite",
        Title = "Comm test site",
        SiteDesign = CommunicationSiteDesign.Topic,
        Owner = "tenantadmin@myTenant.onmicrosoft.com",
        AllowFileSharingForGuestUsers = false,
        Description = "comm site description",
        Lcid = 1033
      };
      var result = context.CreateSiteAsync(siteCreationProperties).Result;

I seems all work fine with SetAuthenticationCookies case.

With request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken); wrong response with status code 3.

It is bug?
Can I create site only with app only access token without authentication cookie?

**Comment by keithtuomi** [comment]
@Maksim-Ilyenia Did you find a resolution to this?

**Comment by jansenbe** [comment]
Have seen this as well and reason was that a site with the same URL still existing in the recycle bin. Can you verify with Get-SPODeletedSite that the site url you want to use is free for use?
