### ISSUE TITLE
Business Starter Intranet Search fails after adding Intranet Static Page

### ISSUE THREAD

**Issue by jbarrar** [SharePoint/PnP#1736]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
After navigating to Site Contents / Pages, I added a new Intranet Static Page. I then checked out the page, currently in draft.  I chose "Edit Properties" and placed one line of text in the Page Contents. I then checked in a Major Version. I then chose approve. I did all of this from within the Site Contents section of SharePoint. I did not navigate to the page and then choose "Edit Page".

#### Observed Behavior
If I enter a word that is in the single line of text in the Page Contents section of the static page, The Search results look like this (I clicked Show Error):
![image](https://user-images.githubusercontent.com/26453530/34423203-6f41f05a-ebe8-11e7-80aa-a1ac2b4f539a.png)
I could not find a way to attach a PublishingImage to the page to eliminate this error.

#### Steps to Reproduce
This seems to happen if any Static Page shows up in search results. If I only hit on News or Events, they display correctly.  The workaround that I have used is to edit the Search.aspx page. Editing the Search Results Web Part, changing the Display Templates to "Use a single template to display items" and changing Best Bet Item to the second "Intranet Search Page Item"

This seems to return basically identical results for News as before but allows Static Pages to show up correctly in Searches. Am I doing something wrong? I believe I've followed the instructions in the premium documentation.

**Comment by jbarrar** [comment]
I also noticed that the failure only seems to occur if the only search results returned are Static Pages. If there are multiple items returned and one or more of those items are News Pages, the search results are rendered correctly and look the same as it I change the display template on the web part to "Intranet Search Page Item".

**Comment by FranckyC** [comment]
Hi @jbarrar, I've made a PR with the fix. If you don't want to wait, you can just add manually the "if" condition for each display template (see the [PR content](https://github.com/SharePoint/PnP/pull/1737/commits/c94a11831f78234b91c602a36700d2369b248ee8)). Then just re upload them in the /_catalogs/masterpage/Display%20Templates/Search/PnP folder. You should be fine.

Let me know if you have questions.

Franck.

**Comment by jbarrar** [comment]
Made the changes now and they worked as expected. Makes perfect sense when the answer is highlighted in green... Thanks!
