### ISSUE TITLE
Starter Intranet Homepage WebParts Not Loading

### ISSUE THREAD

**Issue by Peter-Fell-NHSArdenGEM** [SharePoint/PnP#1741]
FAO @FranckyC 
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: N/A

#### Expected or Desired Behaviour
Carousel Script Editor WebPart and Latest News WebPart should load on homepage.

#### Observed Behaviour
Neither the Carousel or Latest News are loading correctly, leaving blank areas of the page.  No changes have been made to the page or JS that would cause the issue.  This issue is **occurring on two different tenants**.
![pnp intranet webparts](https://user-images.githubusercontent.com/35455177/34943176-797d5b96-f9f2-11e7-997c-8e678128cf7f.PNG)

There are pages to display in the Latest News WebPart, and there are Carousel items to display.  The HTML in the DOM suggests that code is being injected between the <component-carousel> tags but the items aren't being pulled through.
![pnp intranet webparts dom](https://user-images.githubusercontent.com/35455177/34943974-b21138e4-f9f5-11e7-8c3a-4c75d2896d97.PNG)

#### Steps to Reproduce
Unknown - we came back to testing the new intranet solution after a couple of weeks and the WebParts weren't loading.  I do not believe any of the three users who have access to the testing site caused the issue.

I'm happy to collect additional information and go through any troubleshooting steps needed get to the root cause of this issue.

**Comment by Peter-Fell-NHSArdenGEM** [comment]
Update - So the news WebPart not showing news content was a user issue.  We didn't realise ticking the "News on Top" box took the news item out of the homepage news feed.  (We should have agreement from management to buy a copy of the documentation soon).

The carousel issue isn't affected and still isn't loading items.

**Comment by FranckyC** [comment]
Hi @Peter-Fell-NHSArdenGEM,

Did you check your carousel items are not expired (i.e. the "Item Display End Date"/"Item Display Start Date" columns)? I see there is no items retrieved so it means the request didn't catch any elements from the carousel list.

Let me know.

**Comment by Peter-Fell-NHSArdenGEM** [comment]
Oh dear - I'm so sorry - that such a rookie oversight.

Thank you for your help and the quick response.

**Comment by FranckyC** [comment]
@Peter-Fell-NHSArdenGEM No problem ;)
