### ISSUE TITLE
Attribute for ClientSidePage header image (BannerImageUrl) not part of a PnP template

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP#1749]
#### Category
[x] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online

When extracting a template from a site with a modern home page, the banner image of the page is not persisted anywhere. The current schema does not persist any attributes for the banner or position of it - or not showing it - which would be useful.

**Comment by agamadrid** [comment]
Hi,

Has this been fixed? Will it be available in the new March release?
Thanks
Regards,

**Comment by jansenbe** [comment]
Not yet, we plan to include this in our new schema (most likely in May timeframe).

**Comment by JWiersema** [comment]
like

**Comment by MalteJohansson** [comment]
Did this get included in the May update or was it postponed? Can't seem to find any reference to it. @jansenbe

**Comment by jansenbe** [comment]
Yes, header image configuration (which then also sets bannerimageurl) is part of the 2018-05 schema and the May release.
