### ISSUE TITLE
[Azure AD to User Profile Sync Tool] - Sync custom AD properties

### ISSUE THREAD

**Issue by JohnnyKapps** [SharePoint/PnP#1768]
#### Category
[ ] Bug
[ x ] Enhancement

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Using this tool not my car, I noticed that it does not sync custom properties from my Active Directory. Is there any way to synchronize custom AD properties?

**Comment by wils0nk3** [comment]
I would be willing to help get that to work.
