### ISSUE TITLE
Application Lifecycle Management - Site Collection App Catalog

### ISSUE THREAD

**Issue by agamadrid** [SharePoint/PnP#1769]
#### Category
[ ] Bug
**[X] Enhancement**

#### Environment
**[X ] Office 365 / SharePoint Online**
[ ] SharePoint 2016
[ ] SharePoint 2013

Can you please advise when the "Application Lifecycle Management (ALM) APIs" will be available for site colections app catalog?

The below code would be great for site collection catalog.

https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins

https://gautamdsheth.wordpress.com/2017/11/24/automating-add-in-app-installation-using-alm-apis-with-csom-and-powershell-in-sharepoint-online/

Kind Regards,
Thanks

**Comment by VesaJuvonen** [comment]
ALM APIs are now available also for site collection app catalog. Please check the updated documentation from the official docs at https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins. Closing this one.
