### ISSUE TITLE
Wiki: Broken Link: Unit testing for Core Component

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/PnP#1823]
This wiki page "[unit testing for Core Component](https://github.com/SharePoint/PnP/wiki/Unit-testing-for-Core-Component)" contains a broken link.

#### Category
[x] Bug
[ ] Enhancement

#### Expected or Desired Behavior
The link to the Core components should point to the current repository.

#### Observed Behavior
The link to Core components points to: https://github.com/OfficeDev/PnP/tree/master/OfficeDevPnP.Core but should point to: https://github.com/SharePoint/PnP-sites-core

**Comment by maixiu** [comment]
Hi i take this one

**Comment by maixiu** [comment]
oups no, i have no access to the repo's wiki, too bad.

**Comment by jansenbe** [comment]
Thx for reporting this. Just fixed the link
