### ISSUE TITLE
Issue on loading Default Templates from Business.StarterIntranet PNP

### ISSUE THREAD

**Issue by sramakuri** [SharePoint/PnP#1825]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community.
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by sramakuri** [comment]
Category
[ #] Bug
[ ] Enhancement

Environment
[ #] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Am testing the code (PnP/Solutions/Business.StarterIntranet/) on my internat site and facing the issue as below 

Installation started on 10/19/2018 15:39:08
--------------------------------------------------

        Target site: 'https://XXXXXXXXX.sharepoint.com/sites/Pnpintranet'

        Bundling the application (production mode)...           Done!
        Uploading all files in the style library...             Done!
        Configuring the root site...Apply-PnPProvisioningTemplate : Specified method is not supported.
At C:\Users\SatyaRamakuri\Desktop\Intranet\Business.StarterIntranet\Deploy-Solution.ps1:168 char:2
+     Apply-PnPProvisioningTemplate -Path $ProvisioningRootSiteTemplate ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by FranckyC** [comment]
Hi @sramakuri. Try to downgrade your PnP cmdlets version to December 2017 and retry the installation. Let me know.

**Comment by Triaxout** [comment]
I have experienced the same problem and a downgrade of PnP cmdlets didn't help. To be more precisely the script crashed the first time while creating the "Links" list and a second time while creating the "Notifications" list by mentioning an invalid list template. So I created the Links (promoted links) and Notification (custom) lists manually but then i got the same error as @sramakuri. My guess: Binding of content types to a certain list causes the error. Carousel Item binding is the last or only binding which works fine.

**Comment by FranckyC** [comment]
@Triaxout  Is your issue recent? Could it be related? https://github.com/SharePoint/PnP-Sites-Core/issues/1932

**Comment by FranckyC** [comment]
@sramakuri Could you please set the logs to verbose using this command? `Set-PnPTraceLog -On -LogFile traceoutput.txt -Level Debug -Delimiter ","` and show us the output at the error stage.

**Comment by sramakuri** [comment]
@FranckyC  , Thanks for your inputs . I have internal sharepoint domain term store issue . Reassinged term store then script ran successfully. 

Couple of warning messages encountered due to my ExecutionPolicy settings.

FYI : DEMO Output 

Target site: 'https://xxxxxxxxx.sharepoint.com/sites/Pnpintranet'

        Bundling the application (development mode)...          Done!
        Uploading all files in the style library...             Done!
        Configuring the root site...            Done!

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\SatyaRamakuri\Desktop\Intranet\Business.StarterIntranet\Configuration.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\SatyaRamakuri\Desktop\Intranet\Business.StarterIntranet\utility\Utility.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
WARNING: Execute-PnPQuery has been deprecated. Use Invoke-PnPQuery instead.
        Warning: sub web with label en already exists. Use '-UpgradeSubSites' switch parameter to update it. Skipping...
        Warning: sub web with label fr already exists. Use '-UpgradeSubSites' switch parameter to update it. Skipping...
        Configuring image renditions...         Done!
        Adding sample data for the carousel...          Done!

**Comment by FranckyC** [comment]
Cool so everything is working properyl now?
