### ISSUE TITLE
Enable site collection provisioning with CSOM in on-premises farm SP2019

### ISSUE THREAD

**Issue by TomDeu** [SharePoint/PnP#1856]
#### Category
[x] Problem

#### Environment
[x] SharePoint 2019 OnPrem
[x] PnPPowerShell2019 March Release

#### Expected or Desired Behavior
Enable site collection provisioning with CSOM in on-premises farm SP2019
Using code by Vesa Juvonen
_https://blogs.msdn.microsoft.com/vesku/2014/06/09/provisioning-site-collections-using-sp-app-model-in-on-premises-with-just-csom/_

#### Observed Behavior
I got an error when using PNP-Powershell commands: "New-PnPTenantSite: Stub was not found, server did not support API"

#### Steps to Reproduce
1. Using latest PNP PowerShell (msi) March 2019 Release für SP2019
2. Enable site collection provisioning in SP2019 on-premises farm by using this code: 
_https://blogs.msdn.microsoft.com/vesku/2014/06/09/provisioning-site-collections-using-sp-app-model-in-on-premises-with-just-csom/_

3. Try to create a new tenant site by using "New-PnPTenantSite -Url "myUrl" - Title "mytitle" -Owner "myUser" -TimeZone "4"

**Comment by TomDeu** [comment]
Got it, problem solved. It is working now with SP2019

**Comment by matzhoog** [comment]
How did you solve this? Tried the script on the Vesku blog, but still get the error: "New-PnPTenantSite : Cannot find stub for type with id..."
