### ISSUE TITLE
How to add Apps to Sub Sites (SharePoint Online)

### ISSUE THREAD

**Issue by Arioule** [SharePoint/PnP#1864]
#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior

Hi
First, I added 2 apps in my App Catalog
I have managed to add 2 apps using this PNP Template at the Site Collection Level with Apply-PnPProvisioningTemplate Command:

`<?xml version="1.0"?> <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema"> <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.9.1905.1, Culture=neutral, PublicKeyToken=5e633289e95c321a" /> <pnp:Templates ID="CONTAINER-TEMPLATE-0A1917EC9D034839B35926CA424437AC"> <pnp:ProvisioningTemplate ID="TEMPLATE-0A1917EC9D034839B35926CA424437AC" Version="1" BaseSiteTemplate="STS#3" Scope="RootSite"> <pnp:ApplicationLifecycleManagement> <pnp:Apps> <pnp:App AppId="a575ca2d-ef4f-4a52-b32b-c55376d94e86" Action="Install" /> <pnp:App AppId="85b2ef88-43ae-470c-8864-8ffaa737eae4" Action="Install" /> </pnp:Apps> </pnp:ApplicationLifecycleManagement> </pnp:ProvisioningTemplate> </pnp:Templates> </pnp:Provisioning>`

Then I tried to do the same thing at the Sub Site level with the same PNP Template except that I have changed the Scope Value to "Web".
But It did not work.
Did I do something wrong ?

Regards

Thanks for your contribution! Sharing is caring.

**Comment by piasother** [comment]
Did you figure this out? Have the same problem

**Comment by Arioule** [comment]
Not yet. Please, let me know if you figure out before I do.
Thanks

**Comment by Arioule** [comment]
> 
> 
> Did you figure this out? Have the same problem
Not yet. Please, let me know if you figure out before I do.
Thanks

**Comment by Arioule** [comment]
> 
> 
> Did you figure this out? Have the same problem

Not yet. Please, let me know if you figure out before I do.
Thanks

**Comment by piasother** [comment]
Sure thing .Will do.Seems like they not developing further for subsites. And are forcing pple to use flat structure with site collections
