### ISSUE TITLE
Create site collection on-prem without template

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/PnP#284]
Hello,
I am using this code to provision SiteCollection in on-premise.

Using CSOM, I want to create a site collection with "Select template later" option so that I can upload the custom web templates there and create a site based on it.

I get below error, when I pass null as template value:

Specified value is not supported for the SiteCreationProperties.Template parameter.

Could you please guide?

**Comment by tripathiaman** [comment]
Hi Vesa,

Regarding you above comment. Is this still true for SP 2016 or is there any way to create site collection with site template using csom. 

Regards,
Aman
